### ISSUE TITLE
Cascade @AllArgsConstructor and @Delegate broken in Eclipse Mars (4.5.1)

### ISSUE THREAD

**Issue by tan9** [rzwitserloot/lombok#1010]
Following code won't compile by Eclipse 4.5.1 and lombok 1.16.6:

```java
import java.util.Iterator;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.experimental.Delegate;

public class CascadeAllArgsConstructorAndDelegate {

	@AllArgsConstructor
	static class ListWrapper<E> implements List<E>, ListOverrider<E> {

		@Delegate(excludes = ListOverrider.class)
		private final List<E> delegate;

		@Override
		public Iterator<E> iterator() {
			return new IteratorWrapper<E>(delegate.iterator());
		}
	}

	interface ListOverrider<E> {
		Iterator<E> iterator();
	}

	@AllArgsConstructor
	static class IteratorWrapper<E> implements Iterator<E>, IteratorOverrider {

		@Delegate(excludes = IteratorOverrider.class)
		private final Iterator<E> delegate;

		@Override
		public void remove() {}
	}

	interface IteratorOverrider {
		void remove();
	}
}
```

Exception thrown was:
```
java.lang.IllegalArgumentException: startPos = 267 and length is -267.
This breaks the rule that lengths are not allowed to be negative. Affected Node:
java.lang.Object[]
	at lombok.eclipse.agent.PatchDiagnostics.setSourceRangeCheck(PatchDiagnostics.java:33)
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java)
	at org.eclipse.jdt.core.dom.ASTConverter.setTypeAnnotationsAndSourceRangeOnArray(ASTConverter.java:3504)
	at org.eclipse.jdt.core.dom.ASTConverter.convertToArray(ASTConverter.java:3235)
	at org.eclipse.jdt.core.dom.ASTConverter.convertType(ASTConverter.java:3915)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:619)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:207)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3027)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:217)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3027)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1443)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:301)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1216)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:812)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider$1.run(ASTProvider.java:535)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.createAST(ASTProvider.java:528)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.getAST(ASTProvider.java:471)
	at org.eclipse.jdt.ui.SharedASTProvider.getAST(SharedASTProvider.java:128)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:170)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:155)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

The exact code compiles by using javac.

**Comment by ljluestc** [comment]
```

import java.util.Iterator;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.experimental.Delegate;

public class CascadeAllArgsConstructorAndDelegate {

    @AllArgsConstructor
    static class ListWrapper<E> implements List<E>, ListOverrider<E> {

        @Delegate(excludes = ListOverrider.class)
        private final List<E> delegate;

        @Override
        public Iterator<E> iterator() {
            return new IteratorWrapper<E>(delegate.iterator());
        }
    }

    interface ListOverrider<E> {
        Iterator<E> iterator();
    }

    @AllArgsConstructor
    static class IteratorWrapper<E> implements Iterator<E> {

        @Delegate
        private final Iterator<E> delegate;
    }
}
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
```
