### ISSUE TITLE
User-defined enum constant used as lombok.AccessLevel

### ISSUE THREAD

**Issue by jrcw** [rzwitserloot/lombok#1089]
I sometimes get this error using Eclipse Mars 2
The enum constant NOTIFICATION is something from my codebase.
Lombok v1.16.8 "Candid Duck" is installed.

    !ENTRY org.eclipse.jdt.core 4 0 2016-04-19 12:57:12.116
    !MESSAGE Lombok visitor handler class lombok.eclipse.handlers.HandleFieldDefaults failed
    !STACK 0
    lombok.core.AnnotationValues$AnnotationValueDecodeFail: Can't translate NOTIFICATION to an enum of type class lombok.AccessLevel
        at lombok.core.AnnotationValues.guessToType(AnnotationValues.java:287)
        at lombok.core.AnnotationValues.access$200(AnnotationValues.java:41)
        at lombok.core.AnnotationValues$1.invoke(AnnotationValues.java:204)
        at com.sun.proxy.$Proxy31.level(Unknown Source)
        at lombok.eclipse.handlers.HandleFieldDefaults.visitType(HandleFieldDefaults.java:154)
        at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:62)
        at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:223)
        at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:58)
        at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:216)
        at lombok.eclipse.HandlerLibrary.callASTVisitors(HandlerLibrary.java:249)
        at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:187)
        at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:150)
        at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:102)
        at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:111)
        at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:178)
        at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:9959)
        at org.eclipse.jdt.internal.core.util.CommentRecorderParser.endParse(CommentRecorderParser.java:139)
        at org.eclipse.jdt.internal.compiler.SourceElementParser.endParse(SourceElementParser.java:734)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11136)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11461)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.parseStatements(MethodDeclaration.java:194)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:874)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:864)
        at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:10150)
        at org.eclipse.jdt.internal.compiler.SourceElementParser.parseCompilationUnit(SourceElementParser.java:964)
        at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.indexDocument(SourceIndexer.java:108)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:76)
        at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:504)
        at org.eclipse.jdt.internal.core.search.indexing.IndexManager$1.execute(IndexManager.java:984)
        at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:405)
        at java.lang.Thread.run(Unknown Source)

**Comment by rspilker** [comment]
Is it possible that you only get this error if your code is either incomplete or not valid?

**Comment by costamojan** [comment]
Hi @rspilker, 
I'm also experiencing this issue very often and your assumption is right that this happens if the code is incomplete. 
I'm not very deep into the code (not yet), so it would be nice to fill in some blanks for me. The EclipseNode.traverse method performs a check whether the parse is complete or not (this issue happens in an incomplete parse). The presence of this test means that Lombok is supposed to deal with incomplete code although I'm not sure why this might be a good choice. Is there any sense in that?
If that remains a legal situation I would propose to abort the visitation process in HandleFieldDefaults.visitType as we could test for this using EclipseNode. Providing the annotation DeferUntilPostDiet to HandleFieldDefaults might also be a solution but this annotation has method specific meaning.
Please provide me with some feedback. If there's no objection I would provide a pull request for a change.

Best regards

Daniel Kasmeroglu

**Comment by costamojan** [comment]
Just for the record: I've used a self-build variety of Lombok which used my aforementioned check within _HandleFieldDefautls.visitType_ . Unfortunately that didn't solve the issue (maybe caused by invalid Eclipse events; just speculation for now).

**Comment by costamojan** [comment]
Hi @rspilker  or @rzwitserloot (I'm not sure whether someone reacts on issue comments),

I've digged deeper into this issue and I've got a pretty basic sample project now that causes the issue:

* [issue.zip](https://github.com/rzwitserloot/lombok/files/586599/issue.zip)
* Eclipse Neon.1
* Java 8

It's a pretty simple java 8 project reduced to a minimum. I'm currently aware of the cause which is an _EclipseNode_ for an Annotation where the "guessing value" is incorrect. The _FieldDefaults_ annotation of the included _AccountModel_ class is correctly set but somehow the constant of a function call ends up as the annotations level value. I've tried to debug the _EclipseNode_ in order to decide whether this error comes from the Eclipse AST or is located in lombok itself. So far I haven't found any instantiation of _EclipseNode_ with weird values, so I suspect that the issue is located in lombok. Nevertheless I think it's also possible that the Eclipse AST node is altered after the instantiation although I failed to observe this yet.
Since you guys have deeper insides into the code I'm hoping that my feedback helps a little.
Nevertheless I will revisit this issue when I've got the time for it.

**Comment by nlisker** [comment]
Eclipse 4.35.0.I20241217-1800 with Lombok v1.18.35 logs this error when typing `@FieldDefaults(level = AccessLevel.PRIVATE)`. Steps:

1. Create a class.
2. Type `@Fie` and let Eclipse autocomplete to `@FieldDefaults` (this results in a compilation error because the value has not been set yet).
3. Type `(` and press <kbd>ctrl+space</kbd> to see the `level` and the `makeFinal` options, choose the `level` one.
4. The Error Log will log this error:
```
Lombok visitor handler class lombok.eclipse.handlers.HandleFieldDefaults failed
lombok.core.AnnotationValues$AnnotationValueDecodeFail: Can't translate $missing$ to an enum of type class lombok.AccessLevel
	at lombok.core.AnnotationValues.guessToType(AnnotationValues.java:346)
	at lombok.core.AnnotationValues.access$2(AnnotationValues.java:290)
	at lombok.core.AnnotationValues$1.invoke(AnnotationValues.java:262)
	at jdk.proxy10/jdk.proxy10.$Proxy27.level(Unknown Source)
	at lombok.eclipse.handlers.HandleFieldDefaults.visitType(HandleFieldDefaults.java:150)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:73)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
	at lombok.eclipse.HandlerLibrary.callASTVisitors(HandlerLibrary.java:256)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:229)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:187)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:146)
	at lombok.launch.PatchFixesHider$Transform.transform(PatchFixesHider.java:267)
	at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:11448)
	at org.eclipse.jdt.internal.compiler.SourceElementParser.parseCompilationUnit(SourceElementParser.java:996)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:283)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:271)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:246)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:569)
	at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1245)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:182)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:108)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:751)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:816)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1419)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:78)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**Comment by nlisker** [comment]
@rspilker I've added a reproducible test case a couple of months ago. Even if the code is invalid while typing, Lombok shouldn't throw an error.
