### ISSUE TITLE
StackOverflowException during compilation of an absurdly long expression

### ISSUE THREAD

**Issue by mpolajnar** [rzwitserloot/lombok#1171]
In our codebase, we have a piece of generated code that includes an absurdly long expression using a fluent API of some (non-Lombok) builder class, i.e.

`builder.title("x").withHeader(1).blahBlah().etc("hundreds or perhaps thousands of calls").build();
`

When lombok is enabled, compiler chokes with StackOverflowError:

```
Caused by: java.lang.StackOverflowError
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
    at lombok.core.AST.buildWithField0(AST.java:384)
    at lombok.core.AST.buildWithField(AST.java:282)
(... many lines cut out ...)
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
    at lombok.core.AST.buildWithField0(AST.java:384)
    at lombok.core.AST.buildWithField(AST.java:282)
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
    at lombok.core.AST.buildWithField0(AST.java:384)
    at lombok.core.AST.buildWithField(AST.java:282)
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
    at lombok.core.AST.buildWithField0(AST.java:384)
    at lombok.core.AST.buildWithField(AST.java:282)
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
    at lombok.core.AST.buildWithField0(AST.java:384)
    at lombok.core.AST.buildWithField(AST.java:282)
    at lombok.javac.JavacAST.drill(JavacAST.java:345)
    at lombok.javac.JavacAST.buildStatementOrExpression(JavacAST.java:339)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:198)
    at lombok.javac.JavacAST.buildTree(JavacAST.java:65)
```

I know we can increase stack size of the compiler, but that is kind of complicated; we need to do it in IDE for each and every developer, in MAVEN_OPTS on all development machines and on CI machines etc. Could that be improved somehow in Lombok, for example by simulating recursion with a stack on the heap?

**Comment by rspilker** [comment]
I'm closing all duplicates of #1118
