### ISSUE TITLE
"AST must not be null" in Eclipse

### ISSUE THREAD

**Issue by dastamatis** [rzwitserloot/lombok#1177]
In Eclipse (Version: Mars.2 Release (4.5.2) Build id: 20160218-0600), with any version of lombok, if I organize imports on the following class, I get "AST must not be null":
-------
package scratch;

public class Test {
	public Test() {
		lombok.val x = (Object[]) null;
	}
}
-------

I can also reproduce this with String[] and pretty much any array.

**Comment by helenoalves** [comment]
@dastamatis Did you found a solution for this error ?
I'm observed that the error is happening im my eclipse Version: 2018-09 (4.9.0) Build id: 20180917-1800 when I use Organize Imports shortcut using an experimental Annotation @FieldNameConstants, if I put @Wither, or @Acessors it's not happening. 
Lombok version in project is 1.18.4.

Do you have some clue about it ?
Best Regards !

**Comment by helenoalves** [comment]
I updated the project to Lombok 1.18.6 and updated the IDE with lombok's installer and everything is working fine, even with @FieldNameConstants.

**Comment by PauloFerreira25** [comment]
Eclipse IDE Version: 2020-03 (4.15.0)
Build id: 20200313-1211
Lombok v1.18.12

**Comment by sonnesen** [comment]
I'm having this same problem.
Unexpected error in organize imports. See log for detais.
AST must not be null

Version: 2020-03 (4.15.0)
Build id: 20200313-1211
Lombok v1.18.12

The problem occur with the Data annotation and JsonProperty(access = Access.READ_ONLY) annotation.

java.lang.IllegalArgumentException: startPos = 852 and length is -251.
This breaks the rule that lengths are not allowed to be negative. Affected Node:
class org.eclipse.jdt.core.dom.MemberValuePair: access=Access.READ_ONLY
	at lombok.eclipse.agent.PatchDiagnostics.setSourceRangeCheck(PatchDiagnostics.java:36)
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2362)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:2411)

**Comment by renanbaggio** [comment]
Same thing here.. I'm having this problem when I'm using
@JsonProperty(access = JsonProperty.Access.WRITE_ONLY) or any other value from JsonProperty.Access

Unexpected error in organize imports. See log for detais.
AST must not be null

Spring Tool Suite 4 
Version: 4.6.1.RELEASE
Build Id: 202004200639
Lombok v1.18.12 "Envious Ferret"

**Comment by Rawi01** [comment]
#2503 also fixes the `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)` problem, there was a bug in the method that copies the annotation to the generate setter.

**Comment by renanbaggio** [comment]
> #2503 also fixes the `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)` problem, there was a bug in the method that copies the annotation to the generate setter.

Thank you!
