### ISSUE TITLE
log variable unresolved

### ISSUE THREAD

**Issue by saisriram926** [rzwitserloot/lombok#1179]
I am trying to use Lombok SLF4j in one of my projects. `log` variable is not resolved in project which is quite annoying. 
I am using Eclipse Mars, when i installed in Lombok Jar providing eclipse path, my eclipse stopped working. Attached error log

**Eclipse Version:**
``` 
Eclipse Java EE IDE for Web Developers.

Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
```

**System**
Macbook Pro: OSX El Capitan

**Error log**
```
!SESSION 2016-08-02 10:51:09.819 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/kotcs001/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/kotcs001/.eclipse_keyring -showlocation

!ENTRY org.eclipse.osgi 4 0 2016-08-02 10:51:19.248
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1097)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:632)
	at org.eclipse.swt.widgets.Display.getData(Display.java:1458)
	at org.eclipse.ui.internal.WorkbenchPlugin.unsetSplashShell(WorkbenchPlugin.java:1303)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:130)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by danilovEY** [comment]
After a clean installation such an error? May be Eclipse Mars install third-party plugins.

And Eclipse Neon also shut down with this errors?
