### ISSUE TITLE
lombok.bytecode.TestPostCompiler not work

### ISSUE THREAD

**Issue by BorzdeG** [rzwitserloot/lombok#1263]
run `ant clean setupJavaOpenJDK6TestEnvironment test`

result - many errors "Could not initialize class lombok.bytecode.TestClassFileMetaData" and 
> [junit] Test lombok.RunAllTests FAILED
> [echo] All tests successful.

run master branch

**Comment by askoning** [comment]
I recently ran into some test problems, but didn't see this one.
Does the bug still happen? If so, what OS are you using?

**Comment by BorzdeG** [comment]
$ ant -version
Apache Ant(TM) version 1.9.6 compiled on July 8 2015
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
$ uname -a
Linux borz-x220 4.4.0-63-generic #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

KDE Neon

**Comment by askoning** [comment]
Found the problem, and a hack to work around it.

Setting the delombok bootclasspath to the Java 6 runtime (in the `test build target) is only half of what's required to run in a true Java 6 environment. All classes are compiled with the normal JVM used in the rest of the build script, which is typically Java 8 nowadays.

The Java 6 runtime cannot handle the core Java 8 classfiles (complaints about version 52 instead of 50 when loading java.util.RandomAccess). My first try was setting the regular bootclasspath to a Java 6 environment as well, but as something in the test run then tries to use java.lang.invoke.MethodHandle, which is available only from Java 7+, the entire thing breaks down.

With some help from http://stackoverflow.com/questions/11955486/run-ant-task-in-different-jvm I managed to have the entire JUnit target run in a Java 6 environment. The tests then succeed. However, this requires you to have a JDK 6 available somewhere. I don't think we can provide this in the build script, unless we do nasty platform dependent things.

(What I don't understand completely yet, is why this doesn't fail when using the Java 7 test environment, since technically those Java 8 classfiles are also incompatible with Java 7.)

**Comment by askoning** [comment]
Something like:
```
<target name="test6" depends="-loadTestEnvironmentProperties, -failIfNoTestEnvironmentProperties, -test-compile, dist, test-ecj" unless="tests.skip" description="Runs the tests in Java 6.">
	<exec executable="ant">
		<env key="JAVACMD" value="/path/to/jdk1.6.0_45/bin/java"/>
		<arg line="test"/>
	</exec>
</target>
```

**Comment by BorzdeG** [comment]
```bash
$ /usr/lib/jvm/java-6-oracle/bin/java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

$ export JAVA_HOME=/usr/lib/jvm/java-6-oracle/ ; ant -verbose clean setupJavaOpenJDK6TestEnvironment test > test6.log
```

test6.log (cut):
```
Apache Ant(TM) version 1.9.6 compiled on July 8 2015
Trying the default build file: build.xml
Buildfile: /home/borz/Development/lombok/build.xml
Detected Java version: 1.6 in: /usr/lib/jvm/java-6-oracle/jre
Detected OS: Linux
-------------- cut -------------
[ivy:compile] /home/borz/Development/lombok/src/stubs/com/sun/tools/javac/file/PathFileObject.java:6: package java.nio.file does not exist
[ivy:compile] import java.nio.file.Path;
[ivy:compile]                     ^
[ivy:compile] /home/borz/Development/lombok/src/stubs/com/sun/tools/javac/file/PathFileObject.java:11: cannot find symbol
[ivy:compile] symbol  : class Path
[ivy:compile] location: class com.sun.tools.javac.file.PathFileObject
[ivy:compile] 	protected PathFileObject(BaseFileManager fileManager, Path path) {}
[ivy:compile] 	                                                      ^
[ivy:compile] 2 errors
```

**Comment by BorzdeG** [comment]
for the purity of the experiment, I took the last master:

```bash
$ git clone git@github.com:rzwitserloot/lombok.git
$ cd lombok/
$ export JAVA_HOME=/usr/lib/jvm/java-6-oracle/ ; ant -verbose clean setupJavaOpenJDK6TestEnvironment test > test6.log

BUILD FAILED
/home/borz/Development/lombok/build.xml:151: Compile failed; see the compiler error output for details.
        at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1181)
        at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
        at com.zwitserloot.ivyplusplus.Compile.execute(Compile.java:230)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 1 minute 52 seconds

$ export JAVA_HOME=/usr/lib/jvm/java-8-oracle/ ; ant -verbose clean setupJavaOracle8TestEnvironment test > test8.log
    [junit] Test lombok.RunAllTests FAILED
```
