### ISSUE TITLE
Random occurrence: LinkageError: Duplicate Class Definition in eclipse.

### ISSUE THREAD

**Issue by rzwitserloot** [rzwitserloot/lombok#1293]
Every so often, seemingly at random and usually when eclipse starts, this error shows up in the log:

java.lang.LinkageError: loader (instance of  lombok/launch/ShadowClassLoader): attempted  duplicate class definition for name: "lombok/launch/PatchFixesHider$PatchFixes"

at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:448)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.overrideLoadResult(ModuleClassLoader.java:117)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at org.eclipse.jdt.internal.ui.search.OccurrencesFinder.addUsage(OccurrencesFinder.java)
at org.eclipse.jdt.internal.ui.search.OccurrencesFinder.visit(OccurrencesFinder.java:158)
at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:168)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
at org.eclipse.jdt.core.dom.PackageDeclaration.accept0(PackageDeclaration.java:225)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:210)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
at org.eclipse.jdt.internal.ui.search.OccurrencesFinder.performSearch(OccurrencesFinder.java:102)
at org.eclipse.jdt.internal.ui.search.OccurrencesFinder.getOccurrences(OccurrencesFinder.java:108)
at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.updateOccurrenceAnnotations(JavaEditor.java:3338)
at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$6.selectionChanged(JavaEditor.java:3364)
at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:182)
at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:158)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I can't reproduce it which makes it hard to fix.

**Comment by rzwitserloot** [comment]
Lombok v1.16.14 will ship with a potential fix, which... we can't test. It appears to be a race condition where 2 separate threads both try to load the same class simultaneously and this causes us to try to load it twice which doesn't work. The hopeful fix is to catch this error and just try to return the evidently already loaded classes verbatim. Whether that actually fixes the problem..... well, it was already exotic before this fix, but if we get no more bug reports on this, let's close it.

Let's say if nobody fills a bugreport for lombok v1.16.14 or higher on this topic between now and 2017-07-01, let's consider it fixed.

**Comment by rspilker** [comment]
Nobody reported any more problems
