### ISSUE TITLE
1.16.14 broke @Data & @Value annotations in Netbeans

### ISSUE THREAD

**Issue by norrisjeremy** [rzwitserloot/lombok#1299]
The 1.16.14 release no longer displays auto-generated methods (getters/setters/toString/equals/hashCode) inside Netbeans' navigation window, and displays Java syntax errors in other classes that reference any of these auto-generated methods.

**Comment by grimly** [comment]
I may add some more details :

@EqualsAndHashCode and @ToString works.
@Getter and @Setter only works for the first property.
Everything works if we use @Getter and @Setter on all properties.

Something may crash the iteration over class properties for @Getter and @Setter

**Comment by yntelectual** [comment]
I can confirm the problem with 1.16.14 and Netbeans. 

The first property works, the rest does not. IDE log shows the following lombok error:
![untitled](https://cloud.githubusercontent.com/assets/1354787/23298717/028f17cc-fa7f-11e6-8473-e15aec57a206.png)

```
java.lang.NoSuchFieldError: members_field
	at lombok.javac.handlers.JavacHandlerUtil.fixMethodMirror(JavacHandlerUtil.java:962)
	at lombok.javac.handlers.JavacHandlerUtil.injectMethod(JavacHandlerUtil.java:953)
	at lombok.javac.handlers.HandleGetter.createGetterForField(HandleGetter.java:223)
	at lombok.javac.handlers.HandleGetter.generateGetterForField(HandleGetter.java:128)
	at lombok.javac.handlers.HandleGetter.generateGetterForType(HandleGetter.java:94)
	at lombok.javac.handlers.HandleGetter.handle(HandleGetter.java:161)
	at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:109)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:244)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:87)
	at lombok.javac.JavacNode.traverse(JavacNode.java:120)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:83)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:78)
	at lombok.javac.JavacAST.traverse(JavacAST.java:139)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:71)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:294)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:114)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:164)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:74)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:856)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:752)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:99)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1081)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1157)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1210)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1099)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:374)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:311)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:630)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:496)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:163)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:631)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:262)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
java.lang.NoSuchFieldError: members_field
	at lombok.javac.handlers.JavacHandlerUtil.fixMethodMirror(JavacHandlerUtil.java:962)
	at lombok.javac.handlers.JavacHandlerUtil.injectMethod(JavacHandlerUtil.java:953)
	at lombok.javac.handlers.HandleSetter.createSetterForField(HandleSetter.java:203)
	at lombok.javac.handlers.HandleSetter.generateSetterForField(HandleSetter.java:118)
	at lombok.javac.handlers.HandleSetter.generateSetterForType(HandleSetter.java:93)
	at lombok.javac.handlers.HandleSetter.handle(HandleSetter.java:142)
	at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:109)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:244)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:87)
	at lombok.javac.JavacNode.traverse(JavacNode.java:120)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:83)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:78)
	at lombok.javac.JavacAST.traverse(JavacAST.java:139)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:71)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:294)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:114)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:164)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:74)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:856)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:752)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:99)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1081)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1157)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1210)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1099)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:374)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:311)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:630)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:496)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:163)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:631)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:262)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
java.lang.NoSuchFieldError: members_field
	at lombok.javac.handlers.JavacHandlerUtil.fixMethodMirror(JavacHandlerUtil.java:962)
	at lombok.javac.handlers.JavacHandlerUtil.injectMethod(JavacHandlerUtil.java:953)
	at lombok.javac.handlers.HandleGetter.createGetterForField(HandleGetter.java:223)
	at lombok.javac.handlers.HandleGetter.generateGetterForField(HandleGetter.java:128)
	at lombok.javac.handlers.HandleGetter.generateGetterForType(HandleGetter.java:94)
	at lombok.javac.handlers.HandleGetter.handle(HandleGetter.java:161)
	at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:109)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:244)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:87)
	at lombok.javac.JavacNode.traverse(JavacNode.java:120)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:83)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:78)
	at lombok.javac.JavacAST.traverse(JavacAST.java:139)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:71)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:294)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:114)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:164)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:74)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:856)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:752)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:99)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1081)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1157)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1210)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1099)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:374)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:311)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:630)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:496)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:163)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:631)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:262)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
java.lang.NoSuchFieldError: members_field
	at lombok.javac.handlers.JavacHandlerUtil.fixMethodMirror(JavacHandlerUtil.java:962)
	at lombok.javac.handlers.JavacHandlerUtil.injectMethod(JavacHandlerUtil.java:953)
	at lombok.javac.handlers.HandleSetter.createSetterForField(HandleSetter.java:203)
	at lombok.javac.handlers.HandleSetter.generateSetterForField(HandleSetter.java:118)
	at lombok.javac.handlers.HandleSetter.generateSetterForType(HandleSetter.java:93)
	at lombok.javac.handlers.HandleSetter.handle(HandleSetter.java:142)
	at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:109)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:244)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:87)
	at lombok.javac.JavacNode.traverse(JavacNode.java:120)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:83)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:143)
	at lombok.javac.JavacNode.traverse(JavacNode.java:78)
	at lombok.javac.JavacAST.traverse(JavacAST.java:139)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:71)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:294)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:114)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:164)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:74)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:856)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:752)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:99)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1081)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1157)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1210)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1099)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:374)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:311)
	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:630)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:496)
	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:163)
	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:631)
	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:262)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

**Comment by xathien** [comment]
Might already be fixed by [this commit](https://github.com/rzwitserloot/lombok/commit/e3a86782e590e11291e1f208417d5ca61aac4fac).

**Comment by norrisjeremy** [comment]
@xathien I believe you are correct. I just git clone'd and built a 1.16.15 version and confirmed in Netbeans that it is now working correctly. Hopefully 1.16.16 release will be soon?

**Comment by rspilker** [comment]
We're finishing some other jdk9 support issues before shipping a new version.
