### ISSUE TITLE
Compiling class using Lombok with JDK9 doesn't work as advertised.

### ISSUE THREAD

**Issue by schauder** [rzwitserloot/lombok#1372]
Based on #985 I tried to compile the following java file `LombokTest.java`:

```
import lombok.Data;

@Data
public class LombokTest {
  private final int id;
}
```

Using the following command:

     ~/.jenv/candidates/java/9/bin/javac -J--permit-illegal-access -cp /Users/jschauder/.m2/repository/org/projectlombok/lombok/1.16.16/lombok-1.16.16.jar LombokTest.java 

This resulted in the following exception:
```
java.lang.IllegalArgumentException: URI has an authority component
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:99)
	at java.base/java.nio.file.Paths.get(Paths.java:138)
	at lombok.javac.apt.LombokFileObjects$Java9Compiler.wrap(LombokFileObjects.java:142)
	at lombok.javac.apt.LombokFileObjects.createEmpty(LombokFileObjects.java:123)
	at lombok.javac.apt.InterceptingJavaFileManager.getJavaFileForOutput(InterceptingJavaFileManager.java:47)
	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:499)
	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:425)
	at lombok.javac.apt.LombokProcessor.forceNewRound(LombokProcessor.java:333)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:322)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:114)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:164)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:74)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:302)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:162)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:55)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:41)
warning: Can't force a new processing round. Lombok won't work.
LombokTest.java:3: error: package javax.annotation is not visible
@Data
^
  (package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)
LombokTest.java:5: error: package javax.annotation is not visible
  private final int id;
                    ^
  (package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)
2 errors
1 warning
```

JDK version is: 
```
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+166)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+166, mixed mode)
```

Am I doing something wrong? Or did Java9 break something in Lombok?

**Comment by rspilker** [comment]
By default, lombok adds `@javax.annotation.Generated("lombok")` to all generated methods.

Since the new module system, this annotation is no longer standard available.

There are two ways to fix this:

1. Add the following line to you project `lombok.config` file:

        lombok.addJavaxGeneratedAnnotation = false

2. Add ` --add-modules=java.xml.ws.annotation` to your javac command line parameters.

**Comment by schauder** [comment]
I updated my tiny example. The class compiles and I see constructor,` equals` and `toString` in the byte code when I decompile it.

But the warning and the stacktrace still appears. What does the warning mean? Because despite the message 'warning: Can't force a new processing round. Lombok won't work.` Lombok _does_ seem to work.

**Comment by eximius313** [comment]
@rspilker , if it's about `By default, lombok adds @javax.annotation.Generated("lombok") to all generated methods.`

Here is quotation from [JEP](http://openjdk.java.net/jeps/320#Java-EE-modules):
```
some applications rely on the @Generated annotation whose type, 
javax.annotation.Generated, is co-located with JAX-WS in JDK 9. 
(Applications may choose instead to rely on the type 
javax.annotation.processing.Generated that was introduced in Java SE 9)
```

So maybe it would be good, to make that transition?
