### ISSUE TITLE
@EqualsAndHashCode with generic inner class causes compile error

### ISSUE THREAD

**Issue by alexblanck** [rzwitserloot/lombok#1381]
When `@EqualsAndHashCode` is placed on a non-static inner class **and** the inner and outer classes are both generic types, the compilation fails.

Example class:
```java
public class Outer<T> {
    @EqualsAndHashCode
    public class Inner<U> {
    }
}
```

```
javac -classpath lombok.jar Outer.java
Outer.java:6: error: improperly formed type, type arguments given on a raw type
    @EqualsAndHashCode
    ^
```

I encontered the same error while delomboking the file

```
java -jar build/lib/lombok.jar delombok --print ~/Desktop/Outer.java
/Users/blancka/Desktop/Outer.java:4: error: improperly formed type, type arguments given on a raw type
    @EqualsAndHashCode
    ^
Exception in thread "main" java.lang.AssertionError: java.lang.NullPointerException
	at com.sun.tools.javac.code.Symbol$VarSymbol.getConstValue(Symbol.java:1284)
	at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1058)
.....
```

But for some reason, placing a `lombok.config` file in the directory with `lombok.extern.findbugs.addSuppressFBWarnings = true` allowed the delomboking to partially succeed

```
java -jar build/lib/lombok.jar delombok --print ~/Desktop/Outer.java
/Users/blancka/Desktop/Outer.java:4: error: package edu.umd.cs.findbugs.annotations does not exist
    @EqualsAndHashCode
    ^
// Generated by delombok at Wed May 10 14:01:22 PDT 2017
```

```java
public class Outer<T> {

    public class Inner<T> {
        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @edu.umd.cs.findbugs.annotations.SuppressFBWarnings(justification = "generated code")
        @javax.annotation.Generated("lombok")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof Outer.Inner)) return false;
            final Outer.Inner<?> other = (Outer.Inner<?>) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        @edu.umd.cs.findbugs.annotations.SuppressFBWarnings(justification = "generated code")
        @javax.annotation.Generated("lombok")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof Outer.Inner;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @edu.umd.cs.findbugs.annotations.SuppressFBWarnings(justification = "generated code")
        @javax.annotation.Generated("lombok")
        public int hashCode() {
            int result = 1;
            return result;
        }
    }
}
```

The problem here is quite subtle, but one line is incorrect:

```java
final Outer.Inner<?> other = (Outer.Inner<?>) o;
```

should actually be:

```java
final Outer<?>.Inner<?> other = (Outer<?>.Inner<?>) o;
```

**Comment by grignaak** [comment]
This seems to have been introduced in [this commit][1] to fix [this bug][2].

[1]: https://github.com/rzwitserloot/lombok/commit/2335512c8e134a1f6a7a567948543bf87613544b
[2]: https://github.com/rzwitserloot/lombok/issues/1274

**Comment by rspilker** [comment]
Well, the problem is that generics and inner classes don't go well together. Probably, even your handwritten code would be broken. There is no correct way to refer to the generic type of your outer type from the inner class.

We have no plans to fix this.
