### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by JaRJaR55** [rzwitserloot/lombok#1422]
I have an error during runtime: java.lang.NoSuchMethodError
Eclipse Neon2 (JDK 1.8), Runtime (JDK 1.6), Lombok v1.16.6
Clean project, reinstall Lombok, nothing works.

**Comment by victorwss** [comment]
Can you give more information? Like a stacktrace or a minimal code that reproduces the problem? Otherwise, there would be not enough information for someone help you.

**Comment by JaRJaR55** [comment]
This is the stacktrace:
I've decompiled the class too. There aren't the getter/setter methods.

java.lang.NoSuchMethodError: com.project.fibramake.bean.LayerProperties.getLayerPozzettiGuntati()Ljava/lang/String;
	at com.project.fibramake.dao.PercorsiFibraMakeOracleDao.getClosestElement(PercorsiFibraMakeOracleDao.java:1297)
	at com.project.fibramake.bl.PercorsiFibraMakeServiceFacade.getClosestElement(PercorsiFibraMakeServiceFacade.java:331)
	at com.project.fibramake.dwr.PercorsiFibraMakeDwrServiceFacade.getClosestElement(PercorsiFibraMakeDwrServiceFacade.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.directwebremoting.impl.CreatorModule$1.doFilter(CreatorModule.java:172)
	at org.directwebremoting.impl.CreatorModule.executeMethod(CreatorModule.java:184)
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:353)
	at org.directwebremoting.impl.DefaultRemoter.execute(DefaultRemoter.java:306)
	at org.directwebremoting.dwrp.BaseCallHandler.handle(BaseCallHandler.java:110)
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:211)
	at org.directwebremoting.servlet.UrlProcessor.handle(UrlProcessor.java:185)
	at org.directwebremoting.servlet.DwrServlet.doPost(DwrServlet.java:144)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.capgemini.nva.utils.logging.UsernameLogFilter.doFilter(UsernameLogFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:662)

**Comment by omega09** [comment]
What code produces this error?

**Comment by Reshanpubudu5** [comment]
@JaRJaR55 Have you found a solution ?
If so please share since i too have the same and totally F#@$% up

**Comment by Rawi01** [comment]
@Reshanpubudu5 The original issue is most likely some kind of configuration problem that disables lombok during the build. You might face something similar but without further details it is almost impossible to figure out whats wrong. If it worked before check  what you have changed e.g. `*` imports or Java 15 can cause problems. If it never worked you might find some hints on the [setup page](https://projectlombok.org/setup/overview).
