### ISSUE TITLE
[Regression] 1.16.20 does not work with Netbeans < 9

### ISSUE THREAD

**Issue by md-5** [rzwitserloot/lombok#1555]
```
Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/file/BaseFileManager
  	at lombok.javac.apt.LombokFileObjects.getCompiler(LombokFileObjects.java:128)
  	at lombok.javac.apt.InterceptingJavaFileManager.<init>(InterceptingJavaFileManager.java:40)
  	at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:165)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:87)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:510)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:610)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:703)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1049)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1124)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1236)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1123)
  	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:375)
  	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:310)
  	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:629)
  	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:495)
  	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:162)
  	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:631)
  	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:262)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:798)
  	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:725)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:686)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
  	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
  	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
  	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
  Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.file.BaseFileManager
  	at java.lang.ClassLoader.findClass(ClassLoader.java:53...
```

Compiling using Maven, occurs in everywhere lombok is used.
1.16.18 works fine but suffers from #1435 in Netbeans >= 9. Just can't win :(

**Comment by rspilker** [comment]
Can you test this using the [edge release](https://projectlombok.org/download-edge)?

**Comment by md-5** [comment]
Roel,

Looks to be good in all of netbeans 8.1, 8.2 & 9 (at least the old pre-apache build of 9 I'm using).

Closing out as a result,

Thanks!
