### ISSUE TITLE
Compiler errors when using lombok.val in a method that invokespecials a default method

### ISSUE THREAD

**Issue by shoaniki** [rzwitserloot/lombok#1588]
I get a compilation failure if I attempt to build the following cut-down example with e.g. `javac -cp lombok.jar Foo.java`, using Oracle JDK 8 or 9 with any recent Lombok release:

    import lombok.val;
    
    interface Foo {
        default void foo() {
        }
    }
    
    class Bar implements Foo {
        public void foo() {
            Foo.super.foo();  // comment out and it will compile
            val x = 10;       // change val to int and it will compile
        }
    }

Expected result: it would compile and behave identically regardless of whether I use `val` or `int` to declare the variable and regardless of whether the super call is present.

Actual result: compilation crashes with an AssertionError (1.16.20) or a NullPointerException (1.16.18 and previous releases at least as far back as 1.16.8).

The errors appear to be occurring within com.sun code, so I have no idea whether they're actually Lombok's fault or not.

For 1.16.20, the stack traces I'm seeing begin

    java.lang.AssertionError
    	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
    	at com.sun.tools.javac.comp.Resolve.resolveSelf(Resolve.java:3404)
    	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3399)
    	[... snipped 16 more lines in Attr and JCTree ...]
    	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
    	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
    	at lombok.javac.JavacResolution.attrib(JavacResolution.java:238)
    	at lombok.javac.JavacResolution.memberEnterAndAttribute(JavacResolution.java:206)
    	at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java:150)
    	at lombok.javac.handlers.HandleVal.visitLocal(HandleVal.java:126)
    	[... etc ...]

**Comment by andi-huber** [comment]
I was running into the same issue, with following stacktrace

```
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.comp.Resolve.resolveSelf(Resolve.java:3404)
	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3399)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3278)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:1686)
	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1384)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.Attr.visitIf(Attr.java:1582)
	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1269)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at lombok.javac.JavacResolution.attrib(JavacResolution.java:235)
	at lombok.javac.JavacResolution.memberEnterAndAttribute(JavacResolution.java:203)
	at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java:151)
```
Was having a `super` method call and a `val` local variable declaration in the same method, which currently seems causing this.

I'm using latest lombok `v1.18.8`
Issue ocures with maven-compiler-plugin `3.8.1`, I tried 3 different JDK versions
1) openjdk-8 on debian
2) openjdk-11 on debian
3) oracle jdk-8 on debian

However, I'm not seeing any issues, when using lombok with eclipse IDE.

Replacing the `val` with a 'vanilla' local variable declaration solved the issue.

Thanks @shoaniki for the provided 'work-around'.

**Comment by andi-huber** [comment]
See https://github.com/apache/isis/commit/8dabadbcace1e445c9c062d73a65854bf244a0dc for reference.
