### ISSUE TITLE
Building a project transitively depending on Lombok fails on Java 10

### ISSUE THREAD

**Issue by reckart** [rzwitserloot/lombok#1629]
When a project (project A) does not itself make use of lombok but depends on another library (project B) which makes use of lombok, then then the build of project A fails.

```
Caused by: java.lang.ExceptionInInitializerError
	at lombok.javac.handlers.HandleGetter.<clinit>(HandleGetter.java:303)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:171)
	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:156)
	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:44)
	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:89)
	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:674)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:771)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:866)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(JavacProcessingEnvironment.java:110)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1202)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1311)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1250)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:928)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:711)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:422)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:156)
	at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:245)
	at lombok.javac.Javac.<clinit>(Javac.java:155)
	... 49 more
```

The reason is that the lombok library auto-registers a Java annotation processor. 

Fortunately, there is a workaround for project A, which is to disable annotation processing under Java 10:

```
    <profile>
      <id>lombok-fix</id>
      <activation>
        <jdk>[10,)</jdk>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.7.0</version>
              <configuration>
                <!-- Disable annotation processors to avoid build failing on Java 10 with lombok -->
                <compilerArgument combine.children="append">-proc:none</compilerArgument>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>
      </build>
    </profile>
```

This works as long as project A does not need to make use of annotation processors at all. If it needs annotation processors, it might be possible to list the requires processors explicitly: https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessors

**Comment by victorwss** [comment]
AFAIK, lombok is solely an annotation processor tool and should not be used as a runtime dependency to anything that is not another annotation processor tool (and even if this is the case, this is questionable). Many projects that violated this rule already caused many problems downstream elsewhere.

This hints that your Project B is incorrectly configured, because it should not let its dependency in lombok leak out of its build proccess. This could be achieved by something like that (sorry if I get some detail wrong):

```xml
<properties>
    <lombok.version>1.16.20</lombok.version>
</properties>

<pluginManagement>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.7.0</version>
            <configuration>
                <annotationProcessorPaths>
                    <!-- Lombok should be used as an annotation processor. -->
                    <annotationProcessorPath>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>${lombok.version}</version>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</pluginManagement>

<dependencies>
    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${lombok.version}</version>
        <optional>true</optional> <!-- Do not let it leak out as a transitive dependency! -->
    </dependency>
</dependencies>
```

If you aren't allowed to change B's `pom.xml` file, you may try to exclude it from A:

```xml
<dependencies>
    <dependency>
        <groupId>some.group.id</groupId>
        <artifactId>projectb</artifactId>
        <version>${projectb.version}</version>
        <exclusions>
            <exclusion>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
</dependencies>
```

Also, note that if A does uses lombok directly (independently of B), it should also not allow it to leak out of its build proccess, just as I showed in the first snippet above.

**Comment by reckart** [comment]
@victorwss thanks. I have opened an issue with the project through which I acquired the transitive dependency on lombok. Let's see what they say.

**Comment by agibsonccc** [comment]
@victorwss thanks for the clarification, this was definitely our bad. We will implement the proposed fix for our release this week and update. I would say in general you can close this. I will update here if we have any problems.

**Comment by reckart** [comment]
@agibsonccc @victorwss thanks! Closing the issue.
