### ISSUE TITLE
Delombok "Could not find or load main class lombok.core.Main"

### ISSUE THREAD

**Issue by XP1** [rzwitserloot/lombok#1643]
**Delombok "Could not find or load main class lombok.core.Main"**

I am trying to delombok in the command line.

I downloaded lombok.jar version 1.16.20 onto desktop. I followed the command from here:
https://projectlombok.org/features/delombok

```
C:\Users\User\Desktop>java -jar lombok.jar delombok -p File.java
Can't find tools.jar. Rerun delombok as: java -cp lombok.jar;C:\path\to\tools.jar lombok.core.Main delombok -p File.java

C:\Users\User\Desktop>java -cp "lombok.jar;C:\Program Files\Java\jdk1.8.0_162\lib\tools.jar" lombok.core.Main delombok -p File.java
Error: Could not find or load main class lombok.core.Main
Caused by: java.lang.ClassNotFoundException: lombok.core.Main
```

**Comment by randakar** [comment]
Window file paths, the command line and java is not a great combination.
Try escaping those backslashes.

Op vr 6 apr. 2018 13:24 schreef XP1 <notifications@github.com>:

**Comment by XP1** [comment]
I tried different escapes. I even tried copying the "tools.jar" file to desktop, the same directory.

Same error.

```
java -cp "lombok.jar;C:\\Program Files\\Java\\jdk1.8.0_162\\lib\\tools.jar" lombok.core.Main delombok -p File.java

java -cp "lombok.jar;C:/Program Files/Java/jdk1.8.0_162/lib/tools.jar" lombok.core.Main delombok -p File.java

java -cp "lombok.jar;C:^\Program Files^\Java^\jdk1.8.0_162^\lib^\tools.jar" lombok.core.Main delombok -p File.java

java -cp "lombok.jar;tools.jar" lombok.core.Main delombok -p File.java
```

**Comment by XP1** [comment]
I guess [line 82 of `DelombokApp.java`](https://github.com/rzwitserloot/lombok/blob/master/src/delombok/lombok/delombok/DelombokApp.java#L82) needs an update.

However, when I run it on a file such as `GetterSetterExample.java` from:
https://projectlombok.org/features/GetterSetter

I get `NullPointerException`:
```
C:\Users\User\Desktop>java -cp "lombok.jar;C:\Program Files\Java\jdk1.8.0_162\lib\tools.jar" lombok.launch.Main delombok -p GetterSetterExample.java
java.lang.NullPointerException
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:149)
        at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:134)
        at com.sun.tools.javac.file.Locations.access$000(Locations.java:71)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:617)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:643)
        at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.getLocation(Locations.java:577)
        at com.sun.tools.javac.file.Locations.getLocation(Locations.java:678)
        at com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:803)
        at com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:617)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:2750)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:2446)
        at com.sun.tools.javac.jvm.ClassReader.access$000(ClassReader.java:76)
        at com.sun.tools.javac.jvm.ClassReader$1.complete(ClassReader.java:240)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:574)
        at com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:300)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:518)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:258)
        at com.sun.tools.javac.comp.Enter.classEnter(Enter.java:272)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:486)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
        at lombok.delombok.Delombok.delombok(Delombok.java:571)
        at lombok.delombok.Delombok.main(Delombok.java:266)
        at lombok.delombok.DelombokApp.runDirectly(DelombokApp.java:176)
        at lombok.delombok.DelombokApp.runApp(DelombokApp.java:47)
        at lombok.core.Main.go(Main.java:128)
        at lombok.core.Main.main(Main.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at lombok.launch.Main.main(Main.java:36)
```

**Comment by rspilker** [comment]
Hmm, it works on my machine.

What happens if you `run java -version`. Is that also 1.8.0_162?

**Comment by rspilker** [comment]
I think you're running jdk9, while providing a 1.8 tools.jar. I think that that's the problem.

**Comment by XP1** [comment]
You're right. My path variable was pointing to JDK 9. The command works now.
```
"C:\Program Files\Java\jdk1.8.0_162\bin\java.exe" -cp "lombok.jar;C:\Program Files\Java\jdk1.8.0_162\lib\tools.jar" lombok.launch.Main delombok -p GetterSetterExample.java
```
