### ISSUE TITLE
Edge version (1.16.21) does not work on Linux/Mac.

### ISSUE THREAD

**Issue by tmurakam** [rzwitserloot/lombok#1657]
Recent edge version(1.16.21) does not work with JDK10 on Linux system.

Followings is stack trace of build.

```
java.lang.IllegalArgumentException: Problems in URI 'file://lombok/dummy/ForceNewRound0.java' (file://lombok/du                                mmy/ForceNewRound0.java)
        at lombok.javac.apt.LombokFileObjects$Java9Compiler.toPath(LombokFileObjects.java:187)
        at lombok.javac.apt.LombokFileObjects$Java9Compiler.wrap(LombokFileObjects.java:172)
        at lombok.javac.apt.LombokFileObjects.createEmpty(LombokFileObjects.java:157)
        at lombok.javac.apt.InterceptingJavaFileManager.getJavaFileForOutput(InterceptingJavaFileManager.java:4                                7)
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:500)
        at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:426)
        at lombok.javac.apt.LombokProcessor.forceNewRound(LombokProcessor.java:365)
        at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:352)
        at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:115)
        at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:165)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:99)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessing                                Environment.java:972)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProc                                essingEnvironment.java:888)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEn                                vironment.java:110)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvi                                ronment.java:1212)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingE                                nvironment.java:1321)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1253)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:931)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
Listening for transport dt_socket at address: 8000
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:                                117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:                                81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreade                                dBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java                                :43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:99)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at lombok.javac.apt.LombokFileObjects$Java9Compiler.toPath(LombokFileObjects.java:185)
        ... 47 more
```

**Comment by tmurakam** [comment]
Sorry, this problem occurs not only JDK10, but JDK8.
I changed the title.

**Comment by tmurakam** [comment]
I think this is degrade of #1617 fix.

It seems that Paths.get(URI) does not accept "file://lombok/..." form, it should be "file:///lombok/...".
On windows (and maybe mac?)  it does not cause any errors.

**Comment by tmurakam** [comment]
I does not work on Mac too.

**Comment by victorwss** [comment]
Well, the commit that added "file://" was mine, to fix a bug in Netbeans. It is important to ensure that calling `toURL()` method in the resulting `URI` do not causes an `IllegalArgumentException`.

**Comment by victorwss** [comment]
Looking up at the code of the `LombokFileObjects` class:

```java
		private static Path toPath(LombokFileObject fileObject) {
			URI uri = fileObject.toUri();
			if (uri.getScheme() == null) {
				uri = URI.create("file:///" + uri);
			}
			try {
				return Paths.get(uri);
			} catch (IllegalArgumentException e) {
				throw new IllegalArgumentException("Problems in URI '" + uri + "' (" + fileObject.toUri() + ")", e);
			}
		}
```

I.E. If the `fileObject` produces a bad `URI`, it is then fixed there. This makes me question, why the `fileObject` could ever produce a bad `URI` to start with?

I agree that I should had put "file:///" instead of "file://", sorry for that. But it seems that this `if` should not be there. No `LombokFileObject` should ever produce an `URI` that fails either with the `URI.toURL()` or with the `Paths.get(URI)`.

By the way, wouldn't it be better to put this method as an instance method of `LombokFileObject` instead of a static method somewhere else?

**Comment by rspilker** [comment]
Thanks for testing the edge release. We'll release a new one tonight.

**Comment by rspilker** [comment]
The reason we cannot put the method in LombokFileObject is because Path is not present in java 6, and lombok so far is still compatible with java 6.
