### ISSUE TITLE
Lombok can't invoke Java 8 compiler if isFork=true in Gradle 4.7

### ISSUE THREAD

**Issue by timtelcik** [rzwitserloot/lombok#1671]
## Issue

Lombok can't invoke Java 8 compiler if isFork=true in Gradle 4.7.

This issue is related to Gradle issue 1603:
** Lombok can't invoke compiler if isFork=true in Gradle 4.6
*** https://github.com/rzwitserloot/lombok/issues/1603

## Environment

* This java compiler fork issue also affects Gradle 4.7 + JDK 1.8.0_171 + Apple Mac OS 10.12.6

```
$ gradle -version

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Mac OS X 10.12.6 x86_64


$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

## Java Compiler Log

```
$ gradle build --stacktrace

> Task :Code:Common:AdrDomainModels:compileJava
.../src/main/java/XXX/Address.java:63: warning: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
public class Address implements Identifiable, Serializable {
       ^
        at lombok.javac.apt.Processor.init(Processor.java:84)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.call(IncrementalAnnotationProcessingCompileTask.java:76)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:88)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:76)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.processing.JavacProcessingEnvironment
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 43 more
XXX/Address.java:184: error: cannot find symbol
                return getAddressIdentificationNumber();
                       ^
  symbol:   method getAddressIdentificationNumber()
  location: class Address
XXX/Address.java:189: error: cannot find symbol
                getLandAddresses().add(landAddress);
                ^
  symbol:   method getLandAddresses()
  
...

53 errors
1 warning

> Task :Code:Common:AdrDomainModels:compileJava FAILED

FAILURE: Build failed with an exception.  
```

## Workaround

* Disable gradle java compilation forking.

e.g.

{code}
        compileJava {
            options.fork = false
            options.incremental = false
        }
{code}

**Comment by victorwss** [comment]
You need to use Java9+ to compile lombok!

**Comment by timtelcik** [comment]
Hello Victor,

I can use Gradle 4.7 + Lombok 1.16.6 (or 1.16.20) + JDK 1.8.x + MS Windows 7,
but cannot use Gradle 4.7 + Lombok 1.16.6 (or 1.16.20) + JDK 1.8..x + Apple Mac OS 10.12.6
with Gradle compiler options.fork=true.

So, for MS Windows 7, the lombok compilation is OK, but for Mac OS the lombok compilation fails.

Are you advising Java 9.x is required for Mac OS?

Regards,

Tim

**Comment by Maaartinus** [comment]
@timtelcik To get a user notified, you need to mention them like this: @victorwss

**Comment by victorwss** [comment]
See #1659.

**Comment by timtelcik** [comment]
Thanks for the update, @Maaartinus.

The exception states that class "com.sun.tools.javac.processing.JavacProcessingEnvironment" cannot be located, however the stack trace includes class "com.sun.tools.javac.processing.JavacProcessingEnvironment".

My interpretation (based on that information only) is the compiler loses state/context when the compiler thread is forked.

Something weird going on with forking when using JDK 1.8.x (8.x) with Mac OS X 10.12+.

For now, I have a workaround.

Thanks,
Tim

**Comment by timtelcik** [comment]
Hello @Maaartinus and @victorwss,

Further investigation indicates this issue is related to using Gradle 4.6 or Gradle 4.7.

I am now seeing the same compiler forking issue for MS Windows 7 and Mac OS 10.12 with JDK 1.8.x. 

I will submit a Gradle defect and link it back to this issue for other readers. 


Regards,

Tim

**Comment by timtelcik** [comment]
Thanks for the update, @rzwitserloot,

maybe we can progress to a solution via Lombok issue 1603 at

Lombok can't invoke compiler if isFork=true in Gradle 4.6

https://github.com/rzwitserloot/lombok/issues/1603


Regards,

Tim

**Comment by BigSully** [comment]
Gradle 4.5.1 solve the problem.
