### ISSUE TITLE
Delombok broken - duplicate shorthand arg defined

### ISSUE THREAD

**Issue by cptwunderlich** [rzwitserloot/lombok#1705]
Delombok doesn't work anymore, at all, since v1.16.22:

```
java -jar C:\Users\bm\Downloads\lombok.jar delombok
java.lang.IllegalArgumentException: Both classpath and onlyChanged contain the shorthand c
        at com.zwitserloot.cmdreader.ParseItem.makeShortHandMap(ParseItem.java:156)
        at com.zwitserloot.cmdreader.CmdReader.<init>(CmdReader.java:77)
        at com.zwitserloot.cmdreader.CmdReader.of(CmdReader.java:91)
        at lombok.delombok.Delombok.main(Delombok.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at lombok.delombok.DelombokApp.runApp(DelombokApp.java:55)
        at lombok.core.Main.go(Main.java:128)
        at lombok.core.Main.main(Main.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
```

If you look at Delombok.java, both  ([classpath](https://github.com/rzwitserloot/lombok/blob/effa4e9474faf7e2faae89f55f8b3288bb92c69c/src/delombok/lombok/delombok/Delombok.java#L130) and [onlyChanged](https://github.com/rzwitserloot/lombok/blob/effa4e9474faf7e2faae89f55f8b3288bb92c69c/src/delombok/lombok/delombok/Delombok.java#L150) have the same shorthand: 'c'.

Suggested fix: Use a different shorthand, e.g., "o", which is not taken yet and create a regression test, which starts Delombok simply without args.

**Comment by ketan** [comment]
+1. I'm able to reproduce the same error at my end.

**Comment by rspilker** [comment]
Regression tests are welcome, but we do not have an infrastucture for those yet.
