### ISSUE TITLE
onlyExplicitlyIncluded does not work neither JDK 8 nor JDK 9 (might be Gradle issue)

### ISSUE THREAD

**Issue by soberich** [rzwitserloot/lombok#1709]
A simple 1 file of java code with 1.16.22

```java
public class Main {

    public static void main(final String[] args) {
        System.out.println(new A( 1L, "Jack").equals(new A(1L, "Jill")));
        System.out.println(new A());  //should work with no-arg constructor
    }

    @Value
    @Builder
    @EqualsAndHashCode(onlyExplicitlyIncluded = true)
    public static class A {

        Long id;
        @EqualsAndHashCode.Include
        String name;
    }
}
```

causes
```java
> Task :compileJava FAILED
C:\Users\Admin\IdeaProjects\__TEST\testChains\src\main\java\org\javaee8\validation\Main.java:14: error: Can't translate a class java.lang.Boolean to the expected class java.lang.Boolean
    @EqualsAndHashCode(onlyExplicitlyIncluded = true)
                                                ^
1 error


```
stacktrace
```java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:52)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:156)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:141)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:114)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 29 more


```

**Comment by kwonnamsonwwh** [comment]
The same problem happens in Intellij Idea(Not only gradle).

**Comment by cosmicdan** [comment]
So just to confirm, this didn't make it in time for 1.18?

I don't get an error, but setting onlyExplicitlyIncluded to true has no effect - the equals and hashcode methods are still using all fields (when I run Delombok in IntelliJ).

**Comment by soberich** [comment]
Delombok in IntelliJ use a lombok-intellij-plugin and it always worked horrible (not saying that at least it uses older version of lombok which doesn't know new stuff). Use the 'java -jar lombok.jar..' It will produce the proper result.

**Comment by cosmicdan** [comment]
That makes sense. Though if the IntelliJ plugin has this problem, does it
also mean that this will behave the same way when I Run/Debug from within
IntelliJ? If so, then I will have to avoid these particular things until
the plugin itself updated/fixed...

**Comment by sierracc** [comment]
I still see this problem in 1.18. I slightly rewrote the test from above

```
public static void main(final String[] args) {
     System.out.println(new A( 1L, "Jack").equals(new A(1L, "Jill")));
 }

@Value
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public static class A {
     @EqualsAndHashCode.Include
     Long id;
        
     @EqualsAndHashCode.Exclude // Bug happens no matter if this is set or not
     String name;
}
```

Output:
`false`

Should be true as the id should be the only field included.

"onlyExplicitlyIncluded" is completely disregarded. It also doesn't matter if the field is annotated with "@EqualsAndHashCode.Exclude", the field is always included.

This is a very problematic bug causing hard to track down problems in production when .equals() shows unexpected behaviour. Just noticed it by chance having a detached JPA entity where equals() throwed an exception trying to walk an excluded, lazy-loaded relation field in order to calculate the hash. So please add a test case or remove the option altogether if doesn't work reliably.

**Comment by soberich** [comment]
@sierracc This is correct ) (AFAIK)
In 1.18 it IS broken. So you need to update to 1.18.4.

**Comment by sierracc** [comment]
@soberich: Thanks, the I missed posting the minor version.
Actually I'm seeing this in current **1.18.6** with Eclipse+Maven.

**Comment by rzwitserloot** [comment]
Cannot reproduce. Tried in both eclipse2019.03 and javac12 with 1.18.7 (current master branch):

```java
package test;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Value;

@Value
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Test {
	@EqualsAndHashCode.Include String x;
	String y;
	
	public static void main(String[] args) {
		System.out.println(new Test("a", "b").equals(new Test("a", "c")));
		System.out.println(new Test("a", "b").equals(new Test("b", "b")));
	}
}
```

**Comment by d2k2-git** [comment]
I am using Lombok 1.18.6

@ToString(onlyExplicitlyIncluded = true)

can not compile:
`Can't translate a class java.lang.Boolean to the expected class java.lang.Boolean`

**Comment by janrieke** [comment]
I'm confused: What other option is there beside a) putting Lombok in the module POM, and b) putting it in the parent POM?

**Comment by d2k2-git** [comment]
@janrieke 

i had this case which lead to the compile error (" can't translate a class...")

```
parent 
 |--module_commons <- put here the lombok dependency
 |--module_a <- using module_commons.
 |--module_b
```

module_a was using (onlyExplicitlyIncluded = true)

**Comment by janrieke** [comment]
That's a setup which is not supported. Lombok must be added as `provided` dependency, and those dependencies are not transitive.
You have to declare the Lombok dependency explicitly, either in the module or parent POM.
