### ISSUE TITLE
"@Slf4j" annotation ignored in Groovy class [Lombok v1.18.0]

### ISSUE THREAD

**Issue by aplatypus** [rzwitserloot/lombok#1776]
I have an two examples of the same `main` program saved as 
*  TestContextGroovy.groovy
*  TestContextJava.java

Both files sit side-by-side in the same project with a Gradle build.  The Java version works as expected and writes log messages.  When I run the Groovy version I get the stack trace below.  The program crashes on the first use of **`log`** at line **A**.

- **MissingPropertyException**: No such property: **log** for class: 

In my searching I found several examples of Lombok annotations in Groovy code.  So I figured this "should work" and it is a bug.  _Otherwise_, please set me straight if there's some kind of extra thing(s) I need to to to use Lombok with Groovy under Gradle.

```
java.lang.ExceptionInInitializerError
Caused by: groovy.lang.MissingPropertyException: No such property: log for class: au.com.fourtel.tmacs.unittest.TestContextGroovy
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at au.com.fourtel.tmacs.unittest.TestContextGroovy.<init>(TestContextGroovy.groovy:124)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:239)
	at au.com.fourtel.tmacs.unittest.TestContextGroovy.<clinit>(TestContextGroovy.groovy:104)
```

Same code as Groovy and as java ...

Groovy version:
```
@Slf4j                                             
class TestContextGroovy {                          

    private static final    TestContextGroovy   myself       = new TestContextGroovy();

    public TestContextGroovy()
    {
        log.debug( "  TestContextGroovy c'tor called." );    //  A ... fails
    }
    
    public static void main( String... args)       
    {                                              
        myself.testOne();
    }                                              
}                                                  
```

Java version:
```
@Slf4j                                             
class TestContextJava {

    private static final    TestContextGroovy   myself       = new TestContextGroovy();

    public TestContextGroovy()
    {
        log.debug( "  TestContextGroovy c'tor called." );   //  A ... works
    }
    
    public static void main( String... args)       
    {                                              
        myself.testOne();
    }                                              
}                                                  
```

**Comment by rzwitserloot** [comment]
groovy does not support or have lombok. What it does have, is lombok-inspired annotations. So, yeah, what you're trying to do probably should work, but we can't fix it; lombok is not actually included in groovy.
