### ISSUE TITLE
Eclipse + Lombok + Save Actions: The save participant caused an exception

### ISSUE THREAD

**Issue by mad-pojo** [rzwitserloot/lombok#1790]
I use Eclipse Oxygen 4.7.3a and Lombok 1.18.0.
Using annotation @EqualsAndHashCode causes a problem with save actions (the exception org.eclipse.text.edits.MalformedTreeException throws). When i turn off the option "Save Actions / Additional actions / Code Style / Use parentheses in expressions" save actions perform well.

**Comment by rzwitserloot** [comment]
That's probably eclipse attempting to 'fix' the style generated by lombok. We can't just adopt your style as that'd mean that people who use save actions to enforce the opposite style then get a bug.

The only fix is to make this particular save action simply skip generated code, but that's not the easiest thing to make happen, unfortunately.

Accepted, but low priority.

**Comment by d2k2-git** [comment]
is it somehow possible to let eclipse skip the "save actions" for the generated lombok code? the latest eclipse update broke the @Builder annotation when using the "save action" "Add 'this' quialifier to unqualified field accesses".

**Comment by arbitorius** [comment]
Same problem here.
I dug a bit deeper into it.

Environment:
- Eclipse 2019-12 (platform 4.14.0)
- STS 4.5.1
- Lombok edge

Issue occures only with either or both of the following Eclipse save actions from 'Member Access' active:
- Use 'this' qualifier for field access
- Use 'this' qualifier for method access

I found two ways to produce the error:
- @Getter in combination with @EqualsAndHashCode, while either works alone
```
@Getter
@EqualsAndHashCode
public class AtGetterBreaksIt {

	private String testString;

	private Integer testInteger;

}
```

- @Builder.Default on two members 
```
@Builder
@RequiredArgsConstructor
public class SecondAtBuilderDefaultBreaksIt {

	// @Builder.Default
	private final String testString = "";

	// @Builder.Default
	private final Integer testInteger = 0;

}
```

**Comment by Maaartinus** [comment]
> The only fix is to make this particular save action simply skip generated code, but that's not the easiest thing to make happen, unfortunately.

Letting the user tell (in config) Lombok what formatting they use and let Lombok mimic it might be simpler. It's pretty ugly, but can seen as a useful feature for delombok.

**Comment by arbitorius** [comment]
Weird thing is, that it worked on Eclipse platform 4.13.0 without any problems.
So i guess it could also be considered an Eclipse bug, but i thought i could get faster results here.

**Comment by mohanaraosv** [comment]
It seems the problem still exists eclipse and installed lombok-edge version. 

Eclipse IDE for Enterprise Java Developers.
Version: 2019-12 (4.14.0)
Build id: 20191212-1212
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 13


```
!ENTRY org.eclipse.jdt.ui 4 2 2020-03-01 00:36:24.834
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".
!STACK 0
org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)
	at java.base/java.util.Collections.indexedBinarySearch(Collections.java:336)
	at java.base/java.util.Collections.binarySearch(Collections.java:324)
	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)
	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)
	at org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.addEdit(ASTRewriteAnalyzer.java:347)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doCopySourcePreVisit(ASTRewriteAnalyzer.java:1780)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.preVisit(ASTRewriteAnalyzer.java:1759)
	at org.eclipse.jdt.core.dom.ASTVisitor.preVisit2(ASTVisitor.java:170)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2925)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2958)
	at org.eclipse.jdt.core.dom.InfixExpression.accept0(InfixExpression.java:353)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2547)
	at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:299)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2781)
	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:134)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:464)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:458)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2225)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2131)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:593)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:305)
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:294)
	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.attachChange(CompilationUnitRewrite.java:290)
	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.createChange(CompilationUnitRewrite.java:252)
	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:102)
	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:799)
	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.saved(CleanUpPostSaveListener.java:390)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$5.run(CompilationUnitDocumentProvider.java:1650)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.notifyPostSaveListeners(CompilationUnitDocumentProvider.java:1644)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.commitWorkingCopy(CompilationUnitDocumentProvider.java:1424)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$4.execute(CompilationUnitDocumentProvider.java:1503)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider$DocumentProviderOperation.run(TextFileDocumentProvider.java:133)
	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:71)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:76)
	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:66)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.executeOperation(TextFileDocumentProvider.java:461)
	at org.eclipse.ui.editors.text.TextFileDocumentProvider.saveDocument(TextFileDocumentProvider.java:764)
	at org.eclipse.ui.texteditor.AbstractTextEditor.performSave(AbstractTextEditor.java:5052)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.performSave(CompilationUnitEditor.java:1275)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSave(CompilationUnitEditor.java:1329)
	at org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable.doSave(AbstractTextEditor.java:7182)
	at org.eclipse.ui.Saveable.doSave(Saveable.java:213)
	at org.eclipse.ui.internal.SaveableHelper.doSaveModel(SaveableHelper.java:333)
	at org.eclipse.ui.internal.SaveableHelper.lambda$1(SaveableHelper.java:196)
	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2419)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2417)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:260)
	at org.eclipse.ui.internal.SaveableHelper.saveModels(SaveableHelper.java:207)
	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:150)
	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3832)
	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3845)
	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:57)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1201)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1104)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1491)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4881)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4759)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4819)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

**Comment by rzwitserloot** [comment]
We have a bunch of these bug reports. The problem is, there are 3 completely different ways we can fix it:

[1] per issue, adopt contention-free syntax, accept that sometimes it does not exist.

Example: Take the option **Use 'this' qualifier for field access** – if there is no way to configure eclipse to do the opposite, i.e. **Remove unnecessary 'this' qualifiers** or even **remove unnecessary qualifiers** or even **remove unnecessary code**, we can just generate it that way, which has no impact whatsoever on any existing users and now solves this specific variant of the 'overlapping text edits' bug.

If there is an opposite setting (i.e. there is a way to make eclipse use save actions to add a node, as well as one to remove it if it is explicitly present), then this solution is impossible.

[2] per issue, pinpoint patch a fix.

This is quite complicated: Hunt around for the save action's analysis code and patch in an explicit check there to notice it's generated code and skip it. Sometimes this means checking the flag (We do set a flag), sometimes it means skipping any node at a certain position. That last one is not always possible; setting position to 0 or -1 causes other issues. The flag isn't always there either. This is a lot of work and it is hard to be sure that any given fix is going to work on all the many many eclipse versions in active use.

[3] Fix this whole range of issues once and for all.

If we're going to spend a lot of time anyway (as per [2]), why not find a more holistic solution and patch into eclipse a more solid knowledge of the notion of generated AST nodes, fixing them ALL in one fell swoop.

[4] Add formatting config.

I'm loathe to add this to lombok.config; whilst it has benefits for delombok which can also use it, how many people are really going to spend time telling lombok precisely how they prefer to format their code? If there was some standard way to do it I might be interested, but asking users to configure their preferred style in their linter, and then to do it again in their IDE, and then to do it a third time in lombok.config? I don't think we should go down this road.

But what we CAN do, perhaps, is check eclipse's save actions and style config and follow it: Update the eclipse variant of our handler for `@EqualsAndHashCode` and have it actively check the current save action settings and generate according to its preferences.

This also sounds relatively convoluted, but maybe it's not too difficult (a lot depends on whether we have the right objects available to us from which we can navigate to the save action settings. These things tend NOT to be global static variables, and there's the OSGi/equinox module system to consider, which all makes it hard to actually know this stuff).


I'm not sure which of these 4 roads to walk down. I think it's [3], which makes this a big project and not in scope for the next release.

**Comment by MahatmaFatalError** [comment]
I am not sure it this has the same root-cause, but I also have the behaviour that the save action on some classes removes the `@Builder` annotation on classes if there are fields with `@Builder.Default`. See 
![eclipse-lombok-bug](https://user-images.githubusercontent.com/776825/92325968-ecd94a00-f04e-11ea-9b58-dfa74127cea1.gif)

Minimal example:
```java
import static lombok.AccessLevel.*;

import java.util.Collection;
import java.util.ArrayList;

import lombok.AllArgsConstructor;
import lombok.Builder;


@AllArgsConstructor(access = PRIVATE)
@Builder
public class SaveActionLombokBug {
	 
	@Builder.Default
	private Collection<String> test = new ArrayList<>(1);
}
```
