### ISSUE TITLE
java.io.IOException: invalid constant type: 19 at 5

### ISSUE THREAD

**Issue by michaelknurr** [rzwitserloot/lombok#1867]
After upgrading lombok to the latest verion, i get an IOException from another plugin. It may not be a lombok issue but upgrading lombok definitely caused this problem.

By testing several different lombok versions, i could track it down to 1.16.22. My project still works with 1.16.20, but after switching to 1.16.22 maven comes back with an error:

[ERROR] Failed to execute goal de.juplo:hibernate4-maven-plugin:1.1.0:export (default-cli) on project svv-esp: invalid constant type: 19 at 5 -> [Help 1]

Stacktrace:
[INFO] Scanning dependency org.projectlombok:lombok:jar:1.16.22 for annotated classes...
[ERROR] Error while scanning!
java.io.IOException: invalid constant type: 19 at 5
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1236)
        at javassist.bytecode.ConstPool.read(ConstPool.java:1167)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:175)
        at javassist.bytecode.ClassFile.read(ClassFile.java:777)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:118)
        at org.scannotation.AnnotationDB.scanClass(AnnotationDB.java:365)
        at org.scannotation.AnnotationDB.scanArchives(AnnotationDB.java:340)
        at de.juplo.plugins.hibernate4.Hbm2DdlMojo.execute(Hbm2DdlMojo.java:514)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by rspilker** [comment]
Something in the tool chain tries to read `module-info.class` but doesn't understand java 9 bytecode.
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)
