### ISSUE TITLE
NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

### ISSUE THREAD

**Issue by maozzz** [rzwitserloot/lombok#1960]
class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

I'm generate class on fly. Class content:
```Java
public class Plurable5248070682870061718 implements ru.villex.gettext.plurals.Plurable { public int pluralEval(long n) { Object o = (n != 1); if (o instanceof Boolean) { return ((Boolean) o) ? 1 : 0;}else { return (Integer) o;}  }}
```

And then i build Spring Boot app like this: ./mvnw package  -Dspring.profiles.active=test,personal. Build success, but have this errors while testing.

The full code, i'm generate and load class:
```Java
String className = "Plurable";
// create an empty source file
File sourceFile = File.createTempFile(className, ".java");
sourceFile.deleteOnExit();
// generate the source code, using the source filename as the class name
className = sourceFile.getName().split("\\.")[0];
String sourceCode = " public class " + className + " implements " + Plurable.class.getName() + " {"
        + " public int pluralEval(long n) {"
        + " Object o = " + expression + (expression.endsWith(";") ? "" : ";")
        + " if (o instanceof Boolean) { return ((Boolean) o) ? 1 : 0;}else { return (Integer) o;} "
        + " }"
        + "} ";

FileWriter writer = new FileWriter(sourceFile);
writer.write(sourceCode);
writer.close();

// compile the source file
JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
StandardJavaFileManager fileManager = compiler.getStandardFileManager(null, null, null);
File parentDirectory = sourceFile.getParentFile();
fileManager.setLocation(StandardLocation.CLASS_OUTPUT, Arrays.asList(parentDirectory));
Iterable<? extends JavaFileObject> compilationUnits = fileManager.getJavaFileObjectsFromFiles(Arrays.asList(sourceFile));
compiler.getTask(null, fileManager, null, null, null, compilationUnits).call();
fileManager.close();

// load the compiled class
URLClassLoader classLoader = URLClassLoader.newInstance(new URL[]{parentDirectory.toURI().toURL()});
Class<?> plurable = classLoader.loadClass(className);
```

Full trace:
```sh
/var/folders/wz/fgdvz0rj0051rpzxn739dx4m0000gn/T/Plurable3046047388022086712.java:1: warning: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
 public class Plurable3046047388022086712 implements ru.villex.gettext.plurals.Plurable { public int pluralEval(long n) { Object o = 0; if (o instanceof Boolean) { return ((Boolean) o) ? 1 : 0;}else { return (Integer) o;}  }} 
        ^
        at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:426)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:89)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:112)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:165)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at ru.villex.gettext.plurals.ExpressionPlurable.generatePlurableClass(ExpressionPlurable.java:71)
        at ru.villex.gettext.GettextResourceBundle.parseHeaders(GettextResourceBundle.java:106)
        at ru.villex.gettext.GettextResourceBundle.setEntries(GettextResourceBundle.java:79)
        at ru.villex.gettext.GettextResourceBundle.<init>(GettextResourceBundle.java:40)
        at ru.villex.gettext.GettextResourceBundle.<init>(GettextResourceBundle.java:34)
        at ru.villex.gettext.GettextResourceBundle.<init>(GettextResourceBundle.java:30)
        at com.mywed.api.services.TranslationOperations.lambda$reloadTranslations$0(TranslationOperations.java:61)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.processing.JavacProcessingEnvironment
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:422)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 28 more
1 warning
Translation loaded th
```

**Comment by zhouluoyang0406** [comment]
I have this issue too.Do you fix it?

**Comment by ddxygq** [comment]
I have this issue too.Do you fix it?

**Comment by DXShelley** [comment]
I have this issue too.Do you fix it?

**Comment by andrew0213** [comment]
I have this issue too.Do you fix it?

**Comment by andrew0213** [comment]
> Which Javac version is that?

it's  "javac 1.8.0_282" for me.

**Comment by andrew0213** [comment]
> I have this issue too.Do you fix it?



> I have this issue too.Do you fix it?

@zhouluoyang0406 @ddxygq @DXShelley  is anyone fixed this?

**Comment by sick-cat** [comment]
@maozzz @andrew0213 
Have you solved the problem yet ？

**Comment by sick-cat** [comment]
在pom文件中添加：

```xml
<dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.8</version>
          <scope>system</scope>
          <systemPath>${java.home}/../lib/tools.jar</systemPath>
 </dependency>
```
不会再报：NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment
