### ISSUE TITLE
java: lombok.javac.apt.LombokProcessor could not be initialized.

### ISSUE THREAD

**Issue by InterestingSnow** [rzwitserloot/lombok#1982]
jdk1.8 + lombok 1.18.0 + maven 3.5
Warning:(13, 8) java: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderDefault
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:114)
  	at lombok.javac.HandlerLibrary.loadAnnotationHandlers(HandlerLibrary.java:170)
  	at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:155)
  	at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:86)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:54)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:388)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:289)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:197)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:168)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1238)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:912)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:984)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:871)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:696)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:194)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleBuilderDefault
  	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at lombok.launch.ShadowClassLoader.loadClass(ShadowClassLoader.java:418)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at java.lang.Class.forName0(Native Method)
  	at java.lang.Class.forName(Class.java:348)
  	at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
  	... 40 more

**Comment by rspilker** [comment]
Please tell us what you did when this happened. What was your command line?

**Comment by InterestingSnow** [comment]
I am execute mvn install it is happened,my spring boot version is 2.0.7,when my spring boot version is 1.5.8 it is not happende.

**Comment by rspilker** [comment]
If I recall correctly, some versions of spring boot used to include some version of lombok as a transitive dependency. They shouldn't have. I think (or hope) that more recent versions fixed that again. 

Do you still encounter this problem with the current version of spring boot?

**Comment by rspilker** [comment]
Closed due to no feedback from reporter
