### ISSUE TITLE
[BUG] @EqualsHashCode callSuper causes error in Eclipse

### ISSUE THREAD

**Issue by trks1970** [rzwitserloot/lombok#2021]
@EqualsAndHashCode(callSuper=true) results in error in eclipse (4.9)

    @Data
    @EqualsAndHashCode(callSuper=true)
    public class SubClass extends Parent{
        private int attribute;
    }

 - Lombok version: 1.18.4
 - Platform Eclipse 2018-09 (4.9.0)

Log entry:
!MESSAGE Lombok annotation handler class lombok.eclipse.handlers.HandleEqualsAndHashCode failed
!STACK 0
org.eclipse.jdt.internal.compiler.problem.ShouldNotImplement: boolean constant cannot be casted into long
	at org.eclipse.jdt.internal.compiler.impl.Constant.longValue(Constant.java:1513)
	at lombok.eclipse.Eclipse.calculateValue(Eclipse.java:236)
	at lombok.eclipse.handlers.EclipseHandlerUtil.createAnnotation(EclipseHandlerUtil.java:1303)

**Comment by trks1970** [comment]
Sorry, I restarted eclipse, and the error went away.
