### ISSUE TITLE
[BUG] @Wither(onMethod = @__(…)) breaks on current Eclipse throwing NullPointerException from within JDT

### ISSUE THREAD

**Issue by odrotbohm** [rzwitserloot/lombok#2074]
Lombok version is 1.18.6, Eclipse is actually an STS 4.1.2.CI-B1547 (on Eclipse Platform	4.11.0.v20190218-2131).

A standard `@Wither` is fine, adding an `onMethod` attribute causes `NullPointerExceptions`:

```
Java Model Exception: java.lang.NullPointerException
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:324)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:346)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1322)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1281)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:138)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:113)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:93)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:90)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:157)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:92)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
Caused by: java.lang.NullPointerException
```

Let me know if you need any further information.

**Comment by rzwitserloot** [comment]
Can't reproduce. I've used the following (simple blank java project with 1 source file Named Test in it, with 1 dep: lombok):

```java
@Value
public class Test {
	@Wither(onMethod = @__(@Foo)) String x;
	@Wither(onMethod = @__({@Foo})) String y;
}

@Retention(RetentionPolicy.RUNTIME)
@interface Foo {}
```

and then testing that it worked by going to the 'bin' dir of this project and typing `javap -v Test` to see if the withX method exists and contains the annotation.

Are you perhaps not doing the `@__` thing? I find it annoying too but it's the only way to make this work in javac.

eclipse version: Eclipse IDE for Java Developers Version: 2019-03 (4.11.0) Build id: 20190314-1200
lombok: Lombok v1.18.6

**Comment by odrotbohm** [comment]
I can confirm that this works in recent Eclipse versions. Thanks for taking the time to validate, Reinier! 🙏
