### ISSUE TITLE
[BUG] Delombok fails on Java 12

### ISSUE THREAD

**Issue by larsgrefer** [rzwitserloot/lombok#2082]
**Describe the bug**
Running Delombok fails on Java 12 with the following stacktrace:

```
Exception in thread "main" java.lang.NoSuchFieldError: pat
        at lombok.delombok.PrettyPrinter.visitCase(PrettyPrinter.java:1229)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1269)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:244)
        at lombok.delombok.PrettyPrinter.visitSwitch(PrettyPrinter.java:1258)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1225)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:244)
        at lombok.delombok.PrettyPrinter.visitBlock(PrettyPrinter.java:1037)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.visitMethodDef(PrettyPrinter.java:767)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:872)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.printClassMembers(PrettyPrinter.java:578)
        at lombok.delombok.PrettyPrinter.visitClassDef(PrettyPrinter.java:535)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:780)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.printClassMembers(PrettyPrinter.java:582)
        at lombok.delombok.PrettyPrinter.visitClassDef(PrettyPrinter.java:535)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:780)
        at lombok.delombok.PrettyPrinter.print(PrettyPrinter.java:230)
        at lombok.delombok.PrettyPrinter.visitTopLevel(PrettyPrinter.java:485)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:535)
        at lombok.delombok.DelombokResult.print(DelombokResult.java:69)
        at lombok.delombok.Delombok.delombok(Delombok.java:770)
        at lombok.delombok.Delombok.main(Delombok.java:310)
        at lombok.delombok.DelombokApp.runDirectly(DelombokApp.java:177)
        at lombok.delombok.DelombokApp.runApp(DelombokApp.java:48)
        at lombok.core.Main.go(Main.java:130)
        at lombok.core.Main.main(Main.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at lombok.launch.Main.main(Main.java:41)

```

**To Reproduce**
Checkout https://github.com/larsgrefer/joinfaces/commit/60dc36f4a8dfc626e3306b8d2816af3c72f07fe5 and run `./gradlew delombok`

**Expected behavior**
No Exception

**Version info:**
 - Lombok version 1.18.6
- `java --version`:
```
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**Comment by larsgrefer** [comment]
The same error appears using Lombok 1.18.7 (2019-03-26 00:40:19 UTC)

**Comment by rzwitserloot** [comment]
Forget checking out that entire thing, reproducible with simply:

```java
public class SwitchTest {
    @lombok.Getter int makeSureDelombokHasWorkToDo;
    void foo() {
        switch (5) {
        case 5:
        }
    }
}
```

**Comment by rzwitserloot** [comment]
I just pushed an edge release that fixes this and a few other JDK12 issues that popped up. Give it a spin; all should be well. You can even use the fancy new switch expression preview feature and delombok will do its job properly too.

Pushed out to edge-release as well: https://projectlombok.org/download-edge
