### ISSUE TITLE
[BUG] Eclipse 2019.06  Lombok v1.18.6 does not work with Java 12

### ISSUE THREAD

**Issue by Olard** [rzwitserloot/lombok#2169]
**Describe the bug**
When we upgraded from Java 11 to Java 12 we stumbled over a Bug in the `@Builder` generation with the `@Singular` annotation in Eclipse

**To Reproduce**

```(java)
import java.util.List;

import lombok.Builder;
import lombok.Singular;

@Builder
public class Bean {

	@Singular
	public List<Integer> fields;
}
```

**Expected behavior**
Eclipse does not log errors and creates pop-ups like the world is ending.

**Version info (please complete the following information):**
 - Lombok version - 1.18.6 (also 1.18.8)
 - Eclipse 2019-06

**Additional context**
Also happens with Lombok 1.18.8 (+ the additional errors described in https://github.com/rzwitserloot/lombok/issues/2163)

Stacktrace:
```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCode(SwitchStatement.java:438)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:344)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:281)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:579)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:642)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:572)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:649)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:410)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1061)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1100)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:280)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:346)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1322)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:131)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:113)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:93)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:90)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:157)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:92)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
```

**Comment by rspilker** [comment]
Thanks. We didn't work on that yet.

**Comment by rzwitserloot** [comment]
reproduced. 2019-06 standard eclipse-java with java.jdk.net's GA of jdk12 for mac, with that stacktrace.

**Comment by rzwitserloot** [comment]
Eclipse introduced a new field in internal.ast.CaseStatement: constantExpressions. Note the s: plural. We should fill it with a 1-arg array with the same (reference identity) reference as what we already shove into the constantExpression field, IF we find this field with reflection. If we don't find it, don't do anything. That should solve the problem.

**Comment by rzwitserloot** [comment]
@Olard you refer to bug 2163 here. I have not been able to reproduce that; if you can, please add some details as to how to do that :)

**Comment by Olard** [comment]
Yes, I just tried it at home again and the missing detail seems to be setting the project version to 12 (I do that via maven):

    <dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.8</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>12</source>
					<target>12</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

**Comment by Sergey123456** [comment]
> 
> 
> Yes, I just tried it at home again and the missing detail seems to be setting the project version to 12 (I do that via maven):
> 
> ```
> <dependencies>
> 	<dependency>
> 		<groupId>org.projectlombok</groupId>
> 		<artifactId>lombok</artifactId>
> 		<version>1.18.8</version>
> 	</dependency>
> </dependencies>
> <build>
> 	<plugins>
> 		<plugin>
> 			<artifactId>maven-compiler-plugin</artifactId>
> 			<configuration>
> 				<source>12</source>
> 				<target>12</target>
> 			</configuration>
> 		</plugin>
> 	</plugins>
> </build>
> ```

While starting the application, the error appears again

![image](https://user-images.githubusercontent.com/22378271/62617896-9796aa80-b91b-11e9-82e8-119ee88d5242.png)

**Comment by ChristophSchmidt1203** [comment]
Aye, works as expected in 1.18.9 again.
