### ISSUE TITLE
[BUG] Can't generate IntelliJ IDEA project

### ISSUE THREAD

**Issue by christianhujer** [rzwitserloot/lombok#2314]
**Describe the bug**
Tried to generate the IntelliJ IDEA project using `ant intellij`.

**To Reproduce**
```
git clone git@github.com:rzwitserloot/lombok.git
cd lombok
ant deps
ant intellij
```

**Actual behavior**
`ant intellij` stops with an error message. The generated IntelliJ IDEA project does not work (at least not out-of-the-box).

```
BUILD FAILED
/home/christian.hujer/git/nelkinda/lombok/build.xml:395: java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.eclipse.platform#org.eclipse.core.filesystem;[1.3.0,2.0.0)
        at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:811)
        at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.generateLibraryXml(Unknown Source)
        at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.doExecute(Unknown Source)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:271)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.Main.runBuild(Main.java:834)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Total time: 23 seconds
```

**Expected behavior**
`ant intellij` completes successfully. The project is opened in IntelliJ IDEA if possible. If not possible, the project can be opened in IntelliJ IDEA manually. After indexing, `src/*` directories are recognized as source roots.

**Version info (please complete the following information):**
 - Lombok version: master `08faffdf836c8b8d0cca9824bfc32dc1d6a7c2e6`
 - Platform: OpenJDK 13.0.1, IntelliJ IDEA 2019.3
- OS: Linux (Kubuntu 18.04.3 LTS)

**Comment by rzwitserloot** [comment]
The lombok build is sufficiently complicated that, at this point, trying to support intellij as an alternate dev platform is not something we can meaningfully support at this time; none of the core devs work in intellij.

If someone wants to take ownership of the intellij task or some other workable way of hacking on lombok via intellij, we're definitely open to the idea, but I think we better spend our time on fixing bugs and adding features.

Updated build script to reflect this state of affairs. `ant intellij` no longer works and now tells you why.

**Comment by rzwitserloot** [comment]
Fixed (duplicate of issue 1956)
