### ISSUE TITLE
[BUG] Save Action not performed when using @Builder annotation.

### ISSUE THREAD

**Issue by d2k2-git** [rzwitserloot/lombok#2327]
I just updated to the latest Eclipse STS Release 4.5.0 and have a new bug when trying to save files. I am not sure if its a lombok or Eclipse issue.

Using Eclipse Platform Version :  4.14.0.v20191210-0610
Lombok Version: 1.18.10

![image](https://user-images.githubusercontent.com/6248041/71668553-a3bb5280-2d69-11ea-9396-1dffee80fde8.png)

Problem: "Save Actions" will not be performed when using the @Builder annotation.

It seems the option "use 'this' qualifier for field accesses" is causing the bug.

Error log:

> !ENTRY org.eclipse.jdt.ui 4 10006 2020-01-02 13:18:37.568
> !MESSAGE The save participant 'org.eclipse.jdt.ui.postsavelistener.cleanup' caused an exception: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
> !STACK 0
> org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
> 	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:126)
> 	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:1)
> 	at java.util.Collections.indexedBinarySearch(Collections.java:334)
> 	at java.util.Collections.binarySearch(Collections.java:322)
> 	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:799)
> 	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:784)
> 	at org.eclipse.text.edits.TextEdit.addChild(TextEdit.java:340)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.addEdit(ASTRewriteAnalyzer.java:347)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doCopySourcePreVisit(ASTRewriteAnalyzer.java:1780)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.preVisit(ASTRewriteAnalyzer.java:1759)
> 	at org.eclipse.jdt.core.dom.ASTVisitor.preVisit2(ASTVisitor.java:170)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2925)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:433)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteRequiredNode(ASTRewriteAnalyzer.java:845)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2550)
> 	at org.eclipse.jdt.core.dom.Assignment.accept0(Assignment.java:299)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2781)
> 	at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:134)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:464)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:458)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2225)
> 	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:450)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:456)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:2131)
> 	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:593)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisit(ASTRewriteAnalyzer.java:426)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisitList(ASTRewriteAnalyzer.java:464)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.voidVisit(ASTRewriteAnalyzer.java:458)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doVisitUnchangedChildren(ASTRewriteAnalyzer.java:471)
> 	at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1822)
> 	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:430)
> 	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
> 	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:305)
> 	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:294)
> 	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.attachChange(CompilationUnitRewrite.java:290)
> 	at org.eclipse.jdt.internal.corext.refactoring.structure.CompilationUnitRewrite.createChange(CompilationUnitRewrite.java:252)
> 	at org.eclipse.jdt.internal.corext.fix.CompilationUnitRewriteOperationsFixCore.createChange(CompilationUnitRewriteOperationsFixCore.java:102)
> 	at org.eclipse.jdt.internal.ui.fix.CleanUpFixWrapper.createChange(CleanUpFixWrapper.java:39)
> 	at org.eclipse.jdt.internal.corext.fix.CleanUpRefactoring.calculateChange(CleanUpRefactoring.java:799)
> 	at org.eclipse.jdt.internal.corext.fix.CleanUpPostSaveListener.saved(CleanUpPostSaveListener.java:390)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$5.run(CompilationUnitDocumentProvider.java:1650)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.notifyPostSaveListeners(CompilationUnitDocumentProvider.java:1644)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.commitWorkingCopy(CompilationUnitDocumentProvider.java:1424)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider$4.execute(CompilationUnitDocumentProvider.java:1503)
> 	at org.eclipse.ui.editors.text.TextFileDocumentProvider$DocumentProviderOperation.run(TextFileDocumentProvider.java:133)
> 	at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:71)
> 	at org.eclipse.ui.actions.WorkspaceModifyOperation.lambda$0(WorkspaceModifyOperation.java:110)
> 	at org.eclipse.ui.actions.WorkspaceModifyOperation$$Lambda$1315.000000001D7F1080.run(Unknown Source)
> 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
> 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
> 	at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:131)
> 	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:76)
> 	at org.eclipse.ui.internal.editors.text.WorkspaceOperationRunner.run(WorkspaceOperationRunner.java:66)
> 	at org.eclipse.ui.editors.text.TextFileDocumentProvider.executeOperation(TextFileDocumentProvider.java:461)
> 	at org.eclipse.ui.editors.text.TextFileDocumentProvider.saveDocument(TextFileDocumentProvider.java:764)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor.performSave(AbstractTextEditor.java:5052)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.performSave(CompilationUnitEditor.java:1275)
> 	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSave(CompilationUnitEditor.java:1329)
> 	at org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable.doSave(AbstractTextEditor.java:7182)
> 	at org.eclipse.ui.Saveable.doSave(Saveable.java:213)
> 	at org.eclipse.ui.internal.SaveableHelper.doSaveModel(SaveableHelper.java:333)
> 	at org.eclipse.ui.internal.SaveableHelper.lambda$1(SaveableHelper.java:196)
> 	at org.eclipse.ui.internal.SaveableHelper$$Lambda$1318.0000000028EAF010.run(Unknown Source)
> 	at org.eclipse.ui.internal.SaveableHelper.lambda$3(SaveableHelper.java:271)
> 	at org.eclipse.ui.internal.SaveableHelper$$Lambda$1319.0000000028EA3360.run(Unknown Source)
> 	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
> 	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
> 	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2419)
> 	at org.eclipse.ui.internal.WorkbenchWindow$$Lambda$1201.0000000018810F10.run(Unknown Source)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2417)
> 	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:278)
> 	at org.eclipse.ui.internal.SaveableHelper.runProgressMonitorOperation(SaveableHelper.java:260)
> 	at org.eclipse.ui.internal.SaveableHelper.saveModels(SaveableHelper.java:207)
> 	at org.eclipse.ui.internal.SaveableHelper.savePart(SaveableHelper.java:150)
> 	at org.eclipse.ui.internal.WorkbenchPage.saveSaveable(WorkbenchPage.java:3832)
> 	at org.eclipse.ui.internal.WorkbenchPage.saveEditor(WorkbenchPage.java:3845)
> 	at org.eclipse.ui.internal.handlers.SaveHandler.execute(SaveHandler.java:57)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
> 	at sun.reflect.GeneratedMethodAccessor391.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:584)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:653)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:443)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:386)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1201)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
> 	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
> 	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1104)
> 	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1491)
> 	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4881)
> 	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
> 	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4759)
> 	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4819)
> 	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3585)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.ui.internal.Workbench$$Lambda$100.0000000013F34F80.run(Unknown Source)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by d2k2-git** [comment]
Still have this bug in Lombok Version 1.18.12

**Comment by d2k2-git** [comment]
@rzwitserloot 

seems to be caused by a combination of @Builder and @Builder.Default.

Here is a minumum class snippet to let the Save-Action (use 'this' qualifier for field accesses) fail.

```
@Builder
public class SaveActionLombokBug {

	@Builder.Default
	private final String fieldOne = "something";

	@Builder.Default
	private final String fieldTwo = "something";
}
```
