### ISSUE TITLE
[BUG] Updating from 1.16.18 to 1.18.10 breaks

### ISSUE THREAD

**Issue by SElab2019** [rzwitserloot/lombok#2344]
When I try to upgrade lombok from 1.16.18 to version after 1.16.20. There is another code break that failed my test.
```
import org.junit.Assert;
import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


public class lombokTest {
	
    @Test
    public void shouldEncodeWithMixin() {
    	TestUtil test = new TestUtil("1", "2");
        String expected = "{\"_id\":\"1\",\"value\":\"2\"}";
        Assert.assertEquals(expected, JsonParser.encode(test, TestUtilIdMixin.class));
    }

}

@Data
@NoArgsConstructor
@AllArgsConstructor
class TestUtil {
    private String id;
    private String value;
}


class JsonParser {
	
    private static <T> ObjectMapper getObjectMapper(Class<T> value, Class<?>... mixins) {
        final ObjectMapper objectMapper = new ObjectMapper();
        for (Class<?> mixin : mixins) {
            objectMapper.addMixIn(value, mixin);
        }
        return objectMapper;
    }

    public static <T> String encode(T value, Class<?>... mixins){
        if (value == null) {
            return null;
        }
        final ObjectMapper objectMapper = getObjectMapper(value.getClass(), mixins);
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        
    }
    }
}
class TestUtilIdMixin {
    @JsonProperty("_id")
    private String id;
}
```
The test should pass, but it failed with the following stack trace. The jackson version I am using is 2.9.1. 
```
shouldEncodeWithMixin(Se.lab.Demo.lombokTest)  Time elapsed: 0.21 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[_id":"1","value":"2]"}> but was:<{"[value":"2","_id":"1]"}>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at Se.lab.Demo.lombokTest.shouldEncodeWithMixin(lombokTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   shouldEncodeWithMixin(Se.lab.Demo.lombokTest): expected:<{"[_id":"1","value":"2]"}> but was:<{"[value":"2","_id":"1]"}>
```

**Comment by rzwitserloot** [comment]
Field ordering is non-deterministic; JSON generally defines the ordering of keys as non-deterministic as well. The problem is in how you test this stuff; I very much doubt this is lombok's fault.
