### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZenLiuCN** [rzwitserloot/lombok#2468]
**Describe the bug**
`val` for  hold retrun value on call default method on interface;

**To Reproduce**
```java
import lombok.NonNull;
import lombok.val;

import java.util.HashSet;
import java.util.Set;

public interface LombokTest {
    @NonNull
    default Set<String> getSet(){
        return  new HashSet<>();
    }
    interface LombokMiddle extends LombokTest{

    }
    interface LombokThird extends LombokTest{

    }
    class LombokImpl implements LombokThird{
        @Override
        public @NonNull Set<String> getSet() {
         //got error on compile 
//Error:java: Lombok visitor handler class lombok.javac.handlers.HandleVal failed: java.lang.AssertionError
            val set=LombokThird.super.getSet();
            set.add("oh");
            return set;
        }
    }

    public static void main(String[] args) {
        val sets=new LombokImpl();
        System.out.println(sets.getSet().toString());
    }
}
```
here is the stack
```java
java.lang.AssertionError
	at com.sun.tools.javac.util.Assert.error(Assert.java:126)
	at com.sun.tools.javac.comp.Resolve.resolveSelf(Resolve.java:3404)
	at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:3399)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3278)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3250)
	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
	at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1075)
	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
	at lombok.javac.JavacResolution.attrib(JavacResolution.java:235)
	at lombok.javac.JavacResolution.memberEnterAndAttribute(JavacResolution.java:203)
	at lombok.javac.JavacResolution.resolveMethodMember(JavacResolution.java:151)
	at lombok.javac.handlers.HandleVal.visitLocal(HandleVal.java:133)
	at lombok.javac.JavacNode.traverse(JavacNode.java:120)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
	at lombok.javac.JavacNode.traverse(JavacNode.java:105)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:133)
	at lombok.javac.JavacNode.traverse(JavacNode.java:90)
	at lombok.javac.JavacAST.traverse(JavacAST.java:129)
	at lombok.javac.HandlerLibrary.callASTVisitors(HandlerLibrary.java:276)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:81)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:324)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:151)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:201)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:99)
```
**Expected behavior**
+ at least, we may need more exception infomation on which file and lines error happend
+ `val` just not work on INTERFACE.super.MethodCall(); 

**Version info (please complete the following information):**
 * **IDEA Version:** 2020.1
 * **JDK Version:** jdk 1.8_211x64
 * **OS Type & Version:**  windows 7 x64
 * **Lombok Plugin Version:**  0.30-2020.1
 * **Lombok Dependency Version:** 1.18.12

**Additional context**
no more

**Comment by colonelpopcorn** [comment]
I was able to reproduce this as well. I'm going to dig into this one.

**Comment by rzwitserloot** [comment]
`val` is a sizable maintenance headache. I'm wondering if its smarter to just replace it with `final var` and retire the idea that it works on java8. I assume lots of you are using `val` together with java8, right?

**Comment by ZenLiuCN** [comment]
For me,yes. when use java 17,usually use the effective fInally of java, it may ok to only use val for java 8.

**Comment by colonelpopcorn** [comment]
@rzwitserloot
Yes, we're on Java 8. I know I'm comfortable with using `final var` over `val`. `final var` also translates to later versions of Java better than `val` does. Just to clarify are you suggesting dropping `val` entirely in a future release or just for certain Java versions?

**Comment by rzwitserloot** [comment]
Well, `var` was introduced in java 10; you can't use it on 8.

I'm thinking we should detect you're on 10+ and then translate `val` to `final var`. This is ever so very very slightly different from `val`, specifically:

* `val` allows multiple statements; var does not, e.g. `lombok.val x = 5, y = 10;` is legal, `var x = 5, y = 10` isn't.
* `var` will dutifully turn itself into unexpressible types. For example, `var x = new Object() { void foo() {}}; x.foo();` actually works, even though there's nothing you can replace `var` with that makes that work. Similar things happen if you use a ternary op such as `var x = a ? b : c` where b and c share multiple unrelated types (e.g. `Collection & Serializable` - `x` is then all of those types even though `Collection & Serializable x = null;` isn't legal java. `val` can't do those things currently nor are we planning to.

It's very minor. But annoying, in that if we change how  `val` works, it's not _just_ cosmetic / implementation detail. It can in theory break existing usages of `val` or even change behaviour, though that's a really exotic situation if that ends up changing behaviour.

Possibly it'll simply be gated by a setting. `lombok.val.toVar = true` or whatever in `lombok.config`. But then we're really throwing in the towel: The only real point to such a thing is: "We know it causes less problems". I use val a lot myself on eclipse and I fairly aggressively remove it when I see it (replace it with `var`) - because eclipse gets confused a lot more with `val` than it does with `var`. Not when your code is fine, but when you start having syntax errors, eclipse can make sense of what remains less well. Replacing it with `var`, all those issues would go away.

I don't foresee ever just deleting `val` from lombok outright. But I can see a world where we always translate it to `final var`, i.e. if you're on Java 8 it just won't work. It's one of a few reasons I truly severely dislike the line OpenJDK takes on what they think backwards compatibility means - the fact that so many folks are still on JDK8 for plausible reasons is exactly what I said was going to happen when jigsaw was introduced the way it was. Maybe a bit of a cassandra complex thing going on. But it really takes the wind out of the sails for my motivation to work on keeping `val` working properly the way it is set up now (which is a lot of work, it's all very tricky to make it work right).

Point is, so far we've taken the approach of thinking java8 will start being relegated to very low percentages faster than the maintenance burden overwhelms us - so, once java8 hits <5% numbers, just replace the functionality outright with `final var` and be done with it. But, the adoption rate of java8 is holding very steady. So I'm now reconsidering - I no longer think that's right.

That leaves the alternatives:

* Spend the effort.
* Just drop-in replace `final var` automatically on JDK10+. With an opt-out via lombok.config.
* Keep its current behaviour, don't spend the effort, but do add an opt-in to replace it with `final var`.

I'm leaning to the third option, but, __it would mean that `val` without opting in gets `experimental` level bugfix treatment__ - i.e. we aim to fix em but with less focus and time pressure. I think that's pragmatically speaking already how we treat it, because of the above reasons. So please don't advocate against it just because you think it'll motivate us to keep it functioning better than we do now.

**Comment by Rawi01** [comment]
@rzwitserloot We added this replacement some time ago in #2928.

**Comment by ZenLiuCN** [comment]
Our main services are moving to jdk 17 slowly. Can't it be done to translate `val ` with `final var` (this var is lombok.var)?
this is fine with version `1.18.26`  `1.18.28`, And fall on `1.18.24` (using  jdk 1.8u271)
```java
    class LombokImpl implements LombokThird{
        @Override
        public @NonNull Set<String> getSet() {
         //got error on compile 
//Error:java: Lombok visitor handler class lombok.javac.handlers.HandleVal failed: java.lang.AssertionError
           final var oh="oh";
            final var set = LombokThird.super.getSet();
            set.add(oh);
            return set;
        }
    }
```

**Comment by ZenLiuCN** [comment]
Some how it also works use `val`, I just don't know what happened.

**Comment by rzwitserloot** [comment]
(I forgot we already did this, Rawi01 reminded us in a comments 2 up from here) that on lombok 1.18.22 and java 10+, we already replace it with `final var`.  So, just.. shift to jdk17, and all will be well.

**Comment by colonelpopcorn** [comment]
@ZenLiuCN We're using `v1.18.28`.

@rzwitserloot Thanks for the documentation. We've already started a project to upgrade our codebase to Java 17 and it sounds like we'll have better luck using `final var` once we get there.
