### ISSUE TITLE
[FEATURE] Reduce amount of code required to integrate Lombok builders with Jackson

### ISSUE THREAD

**Issue by mtwig** [rzwitserloot/lombok#2532]
The current recommend way to add Jackson + Lombok builders is to create an interface that the Builder class implements. This can require a simple class to have a `@Builder`, an interface that has serialize annotations, and sometimes duplicated annotations that already exist on the field.

It would be nice if a Builder could specify an interface in the annotation, as well as support copying field annotations onto builder setters. 

The end result is less boilerplate code that exists only for Lombok, which is actually meant to _reduce_ boilerplate code.

Using a simple POJO with 2 date fields that need to be serialized / deserialized with different formats. 

Lombok today:
```java
@Data
@Builder
@JsonDeserialize(builder = JacksonLombokIntegration.JacksonLombokIntegrationBuilder.class)
public class JacksonLombokIntegration {

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private final LocalDateTime day;

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-ddTHH:mm:ss")
    private final LocalDateTime time;

    interface JacksonLombokIntegrationMeta {
        @JsonDeserialize(using = LocalDateTimeDeserializer.class)
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
        JacksonLombokIntegrationBuilder day(LocalDateTime day);

        @JsonSerialize(using = LocalDateTimeSerializer.class)
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-ddTHH:mm:ss")
        JacksonLombokIntegrationBuilder time(LocalDateTime time);
    }

    @JsonPOJOBuilder(withPrefix = "")
    static class JacksonLombokIntegrationBuilder implements  JacksonLombokIntegrationMeta {
    }

}
```

Desired code:
```java
@Data
@Builder(useInteface = JacksonLombokIntegration.JacksonLombokIntegrationMeta.class)
@JsonDeserialize(builder = JacksonLombokIntegration.JacksonLombokIntegrationBuilder.class)
public class JacksonLombokIntegration {

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private final LocalDateTime day;

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-ddTHH:mm:ss")
    private final LocalDateTime time;

    @JsonPOJOBuilder(withPrefix = "")
    interface JacksonLombokIntegrationMeta {
    }
}

```

In this particular example, copying annotations removes the requirement to use an interface at all. Allowing the annotation on an interface reduces the number of times a developer will have to define both an interface, and a builder class.

**Comment by janrieke** [comment]
That's what `@Jacksonized` is for. It's in the current snapshot and will be in the next release.

See PR #2387 for details.

**Comment by mtwig** [comment]
> That's what `@Jacksonized` is for. It's in the current snapshot and will be in the next release.
> See PR #2387 for details.
> 
> Furthermore, several Jackson annotations are now copied to the builder setter methods. Set #2419 for details.

Oh fantastic. I didn't find a duplicate when I was searching.

**Comment by janrieke** [comment]
With `@Jacksonized`, your example looks like this:

```
@Data
@Jacksonized
@Builder
public class JacksonLombokIntegration {
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private final LocalDateTime day;

    @JsonSerialize(using = LocalDateTimeSerializer.class)
    @JsonDeserialize(using = LocalDateTimeDeserializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-ddTHH:mm:ss")
    private final LocalDateTime time;
}
```

`@JsonDeserialize` and `@JsonFormat` are copied to the builder setters (`@JsonSerialize` is not, but that does not affect deserialization).

**Comment by cameronbraid** [comment]
Great idea .. found an issue

```
package demo;

import com.fasterxml.jackson.databind.ObjectMapper;

import lombok.Builder;
import lombok.experimental.SuperBuilder;
import lombok.extern.jackson.Jacksonized;

@Builder
@Jacksonized
public class LombokJacksonized {
  
  private String name;
  
  private Foo foo;

  @SuperBuilder
  @Jacksonized
  public static class Thing {

  }
  
  @SuperBuilder
  @Jacksonized
  public static class Foo extends Thing {

  }
  public static void main(String[] args) throws Exception {
    new ObjectMapper().readValue("{\"foo\":{}}", LombokJacksonized.class);
  }

}
```

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `demo.LombokJacksonized$Foo` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"foo":{}}"; line: 1, column: 9] (through reference chain: demo.LombokJacksonized["foo"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1611)
        at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1320)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
        at demo.LombokJacksonized.main(LombokJacksonized.java:29)
```

**Comment by janrieke** [comment]
Please create a new issue for this.

**Comment by cameronbraid** [comment]
Sorry - done https://github.com/rzwitserloot/lombok/issues/2575
