### ISSUE TITLE
[BUG] Lombok causes IntelliJ IDEA errors

### ISSUE THREAD

**Issue by yhan219** [rzwitserloot/lombok#2559]
**Describe the bug**
IDEA‘s info
```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to xxx
You have a perpetual fallback license for this version
Subscription is active until July 8, 2022
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, BashSupport, Gradle View, GrepConsole, GsonFormat, Lombook Plugin, MyBatisLog, QAPlug, QAPlug - Checkstyle, QAPlug - FindBugs, QAPlug - PMD, String Manipulation, com.alibaba.p3c.smartfox, de.kontext_e.idea.plugins.autofill, org.mapstruct.intellij, ideanginx9, io.github.biezhi.plugins.gitmoji, net.vektah.codeglance, uk.co.ben-gibson.remote.repository.mapper, zielu.gittoolbox, mobi.hsz.idea.gitignore, org.sonarlint.idea, com.vladsch.idea.multimarkdown, MavenRunHelper, pro.bashsupport, org.jetbrains.plugins.vue, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.packagesearch.intellij-plugin, com.zhaow.restful.toolkit, com.ccnode.codegenerator.MyBatisCodeHelperPro, izhangzhihao.rainbow.brackets, Pythonid, cn.yiiguxing.plugin.translate, de.endrullis.idea.postfixtemplates
```

my spring boot project config:
gradle
```
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
...

 compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

```
lombok version `1.18.12`

**IDEA log**
```
invalidated at: no info [Plugin: Lombook Plugin] 
com.intellij.diagnostic.PluginException: Element: class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder #JAVA  because: psi is outdated
invalidated at: no info [Plugin: Lombook Plugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:67)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:478)
	at com.intellij.psi.impl.source.resolve.ResolveCache.ensureValidPsi(ResolveCache.java:240)
	at com.intellij.psi.impl.source.resolve.ResolveCache.ensureValidResults(ResolveCache.java:233)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:210)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:185)
	at com.intellij.psi.impl.source.resolve.reference.impl.PsiPolyVariantCachingReference.multiResolve(PsiPolyVariantCachingReference.java:19)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.resolveMethodGenerics(PsiNewExpressionImpl.java:214)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.resolveConstructor(PsiNewExpressionImpl.java:236)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.resolveMethod(PsiNewExpressionImpl.java:137)
	at com.intellij.codeInspection.StringTokenizerDelimiterInspection$1.visitCallExpression(StringTokenizerDelimiterInspection.java:29)
	at com.intellij.psi.JavaElementVisitor.visitNewExpression(JavaElementVisitor.java:184)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:382)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:155)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:147)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$4(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$5(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1105)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:191)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder #JAVA  because: psi is outdated
invalidated at: no info
	... 61 more
2020-08-20 15:47:05,266 [12654854]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2020.2  Build #IU-202.6397.94 
2020-08-20 15:47:05,266 [12654854]  ERROR - aemon.impl.PassExecutorService - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-08-20 15:47:05,266 [12654854]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2020-08-20 15:47:05,266 [12654854]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: Lombok version: 0.30-EAP 
2020-08-20 15:47:05,266 [12654854]  ERROR - aemon.impl.PassExecutorService - Last Action: CompileDirty 

```

**Comment by Rawi01** [comment]
The Lombok IntelliJ plugin is a different project: https://github.com/mplushnikov/lombok-intellij-plugin/. There already is an issue and a comment in the README about your problem.

**Comment by yhan219** [comment]
thank U
