### ISSUE TITLE
[BUG] SneakyThrows doesn't work with JDK 15

### ISSUE THREAD

**Issue by rdwallis** [rzwitserloot/lombok#2579]
**Describe the bug**
When compiling with javac, I get the following warning:

```
error: Error during the transformation of 'foo.bar.SomeClass'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 59
```

**To Reproduce**
```
// Test.java
import lombok.SneakyThrows;
import java.io.IOException;

public class Test {

    @SneakyThrows
    public void testMethod() {
      throw new IOException();
    }

}
```

Run ` javac -cp lombok-1.18.12.jar Test.java` observe output:
```
error: Error during the transformation of 'Test'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 59
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
  	at lombok.bytecode.AsmUtil.fixJSRInlining(AsmUtil.java:37)
  	at lombok.bytecode.SneakyThrowsRemover.applyTransformations(SneakyThrowsRemover.java:46)
  	at lombok.core.PostCompiler.applyTransformations(PostCompiler.java:43)
  	at lombok.core.PostCompiler$1.close(PostCompiler.java:76)
  	at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1507)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:757)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1644)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1612)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:59)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:45)
```

**Expected behavior**
Compilation succeeds

**Version info:**
 - Lombok 1.18.12 or Edge
 - openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

**Additional context**
This is a new version of the https://github.com/rzwitserloot/lombok/issues/2302 bug

**Comment by Rawi01** [comment]
There already is a PR (https://github.com/rzwitserloot/lombok.patcher/pull/6) that might fix this issue.

**Comment by nbittich** [comment]
I ended up by just not using SneakyThrows, and it works fine now.

**Comment by SimSonic** [comment]
> I ended up by just not using SneakyThrows, and it works fine now.

It isn't possible to remove them all in huge project :)

**Comment by nbittich** [comment]
> > I ended up by just not using SneakyThrows, and it works fine now.
> 
> It isn't possible to remove them all in huge project :)

yeah I can imagine, hope there will be a release soon fixing the issue.

**Comment by SimSonic** [comment]
@rzwitserloot Hi, could you give any est. about Java 15 support?

Thanks.

**Comment by kirkch** [comment]
I tested using the latest edge build today (https://projectlombok.org/download-edge), and this issue is still present there.

**Comment by rdwallis** [comment]
Thank you everyone on the Lombok Team.  This appear to be fixed in Lombok 1.18.14

**Comment by jenni** [comment]
hi, we've just upgraded our plugin  to `"io.freefair.gradle:lombok-plugin:5.3.0"` and we are still getting this issue, any workaround for it?

**Comment by JavaWebinar** [comment]
Still exist in 1.18.20!
java.lang.IllegalArgumentException: Unsupported class file major version 59

**Comment by jvasquezv** [comment]
@SneakyThrows doesn't work with JDK 17

 **Observe output:**
`LoggingAspect.java
java: Error during the transformation of 'LoggingAspect'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 61
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
  	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
  	at lombok.bytecode.AsmUtil.fixJSRInlining(AsmUtil.java:37)
  	at lombok.bytecode.SneakyThrowsRemover.applyTransformations(SneakyThrowsRemover.java:46)
  	at lombok.core.PostCompiler.applyTransformations(PostCompiler.java:43)
  	at lombok.core.PostCompiler$1.close(PostCompiler.java:77)
  	at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1508)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:738)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1617)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1585)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:514)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:560)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:512)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:355)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:280)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:234)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1485)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1123)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1268)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1088)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:854)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:441)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:190)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:318)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:146)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Rawi01** [comment]
@jvasquezv It does, you have to use the latest lombok version

**Comment by jvasquezv** [comment]
> @jvasquezv It does, you have to use the latest lombok version

@Rawi01 I am use the last version.
![lombok-version](https://user-images.githubusercontent.com/4551379/155911157-49bfd1a4-024a-4d9c-861d-1bafd22b34f5.png)

**Comment by Rawi01** [comment]
@jvasquezv I'm pretty sure that it still uses an older version for the real build. The only other reason for this is that there is an outdated asm version that gets used instead of the one used in lombok.

**Comment by JahnaviMolleti** [comment]
I have same issue after migrating to java 18 with lombok "post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 62"

**Comment by Rawi01** [comment]
You can use the [edge version](https://projectlombok.org/download-edge) for Java 18 support.
