### ISSUE TITLE
[BUG] lombok makes errorprone throw IndexOutOfBoundsException when use @NonNull and @Getter

### ISSUE THREAD

**Issue by moonfruit** [rzwitserloot/lombok#2713]
**Describe the bug**
When using `@Getter` or `@Value` on the class and @NonNull on the field, google errorprone throw an IndexOutOfBoundsException:

<details>
  <summary>javac output</summary>

```
Test.java:1: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
import lombok.NonNull;
^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.5.1
     BugPattern: SameNameButDifferent
     Stack Trace:
     java.lang.IndexOutOfBoundsException: Range [248, 240) out of bounds for length 263
  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:76)
  	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:295)
  	at java.base/java.util.Objects.checkFromToIndex(Objects.java:385)
  	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:677)
  	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:44)
  	at com.google.errorprone.VisitorState.getSourceForNode(VisitorState.java:551)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.handle(SameNameButDifferent.java:101)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.visitIdentifier(SameNameButDifferent.java:84)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.visitIdentifier(SameNameButDifferent.java:61)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2427)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:509)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitAnnotation(TreeScanner.java:866)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2756)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:509)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitModifiers(TreeScanner.java:854)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2786)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:509)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:222)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1001)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:509)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:189)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:832)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.bugpatterns.BugChecker$SuppressibleTreePathScanner.scan(BugChecker.java:509)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent.matchCompilationUnit(SameNameButDifferent.java:115)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:556)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:59)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:45)
1 error
```

</details>

**To Reproduce**

Get jars:

```
wget https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.16/lombok-1.18.16.jar
wget https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.5.1/error_prone_core-2.5.1-with-dependencies.jar
wget https://repo1.maven.org/maven2/org/checkerframework/dataflow-shaded/3.7.1/dataflow-shaded-3.7.1.jar
wget https://repo1.maven.org/maven2/com/google/code/findbugs/jFormatString/3.0.0/jFormatString-3.0.0.jar
```

Compile it with:

```
javac -classpath lombok-1.18.16.jar:jFormatString-3.0.0.jar:dataflow-shaded-3.7.1.jar:error_prone_core-2.5.1-with-dependencies.jar -XDcompilePolicy=simple -Xplugin:ErrorProne Failed.java
```

Failed.java:

```java
import lombok.Getter;
import lombok.NonNull;

@Getter
public class Failed {
	@NonNull String targetTable;
}
```

Or:

```java
import lombok.Value;
import lombok.NonNull;

@Value
public class Failed {
	@NonNull String targetTable;
}
```

But below two does not throw exceptions:

```java
import lombok.Data;
import lombok.NonNull;

@Data
public class Successful {
	@NonNull String targetTable;
}
```

```java
import lombok.Getter;
import lombok.NonNull;

public class Test {
	@Getter @NonNull String targetTable;
}
```

**Expected behavior**
Expecting that errorprone does not throw exceptions.

**Version info (please complete the following information):**
 - Lombok 1.18.16
 - Error Prone 2.5.1
 - Javac 15.0.1 or 11.0.9

**Comment by moonfruit** [comment]
For Lombok 1.18.18, this does not throw exceptions. Except for that error-prone output a lot of useless warnings.

**Comment by Rawi01** [comment]
Even if it might sounds weird this is the expeceted behaviour :smile:

Every normal node in the Java abstract syntax tree has a start and end position of the actual code. As there is no real code for generated lombok methods these positions get filled with the start and, since 1.18.18, also the end position of the source annotation e.g. `@Getter`. Error Prone uses these positions for some of the checks which leads to some false positives. 

The real solution is to wait for the next Error Prone release, add `-XepDisableWarningsInGeneratedCode` to your compiler args and `lombok.addLombokGeneratedAnnotation = true` to your `lombok.config`.

Context: #2691, https://github.com/google/error-prone/issues/1863

**Comment by moonfruit** [comment]
No, @Rawi01. That using `-XepDisableWarningsInGeneratedCode` and `-XepDisableWarningsInGeneratedCode` do not suppress the warnings generated by error-prone in this scenario.
And by default, lombok already add `@SuppressWarnings("all")`, and this should already disable all error-prone inspections.

**Comment by Rawi01** [comment]
Oh, you are right, it does not work in this case. I think that this is something that has to be fixed in Error Prone, it seems like it ignores the generated annotation. 

`@SuppressWarnings("all")` is not supported in Error Prone, you have to specify the warning you want to suppress. (https://github.com/google/error-prone/issues/329#issuecomment-105615411)

**Comment by moonfruit** [comment]
You're right. Error Prone do not support `@SuppressWarnings("all")`.
