### ISSUE TITLE
[BUG] SuperBuilder with static initializer block throws NullPointerException

### ISSUE THREAD

**Issue by gypsy** [rzwitserloot/lombok#2716]
**Describe the bug**
Using SuperBuilder annotation and including a static initializer block throws NullPointerException as `field.type` is `null` in https://github.com/rzwitserloot/lombok/blob/04f17f4dcfbb0e7881d605708467498e3ec56521/src/core/lombok/eclipse/handlers/HandleSuperBuilder.java#L1096

Full stack trace from Eclipse log:
```
java.lang.NullPointerException
	at lombok.eclipse.handlers.HandleSuperBuilder.gatherUsedTypeNames(HandleSuperBuilder.java:1096)
	at lombok.eclipse.handlers.HandleSuperBuilder.handle(HandleSuperBuilder.java:247)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:267)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:233)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:226)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:185)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:110)
	at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:119)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:190)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11687)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12880)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13104)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13061)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:11448)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:850)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:448)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:345)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:275)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**To Reproduce**
Please use this simple Java program to reproduce the issue:
```
import lombok.Getter;
import lombok.experimental.SuperBuilder;

public class LombokTest2 {

	public static void main(String[] args) {
		One myOne = One.builder().name("Jupiter").build();
		System.out.println("my name is " + myOne.getName());
	}

	@SuperBuilder
	public static class One {
		private static final String world;
		static {
			world = "Hello";
		}
		@Getter
		private final String name;
	}
}
```

**Expected behavior**
Exception should not be thrown when static initializer block is encountered.

**Version info (please complete the following information):**
 - Lombok version: 1.18.17 (also same for 1.18.16)
 - Platform:
   - Eclipse Versions: 2020-09 (4.17.0), 2020-12 (4.18.0)
   - Java info:
   ```
   $> java -version
   java version "11.0.10" 2021-01-19 LTS
   Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
   ```

**Additional context**
Adding a `continue` seems to resolve the issue if `field.type == null`, tested using locally built lombok (please ignore the custom `logger` added to debug the issue (!?):
```
		if (td.fields != null) {
			for (FieldDeclaration field : td.fields) {

				if (field == null) {
					logger.writeLog("field is name. td name: " + String.valueOf(td.name));
				} else if (field.type == null) {
					logger.writeLog("field.type is null. td name: " + String.valueOf(td.name) + " field info: " + field.toString());
					continue;
				} else if (field.type.getTypeName() == null) {
					logger.writeLog("field.type.getTypeName() is null. td name: " + String.valueOf(td.name));
				}
				char[][] typeName = field.type.getTypeName();
				if (typeName.length >= 1) // Add the first token, because only that can collide.
					usedNames.add(String.valueOf(typeName[0]));
			}
		}
```

Log output from the "custom" logger:
```
[2021-01-20T01:41:14.312728][main][lombok.eclipse.handlers.HandleSuperBuilder] field.type is null. td name: One field info: static {
  world = "Hello";
}
```

Please let me know if you'd like me to provide more info.

Thanks for all your help!

**Comment by Rawi01** [comment]
Perfect bug report :+1: 

For some reason eclipse handles initializers as fields (`Initializer` is a subclass of `FieldDeclaration`) and adds all initializers to the `fields` array. Seems like no one expected that :smile:

**Comment by gypsy** [comment]
@Rawi01 Apologies for late response, nowadays the days are passing even faster 😅 
Thank you for looking into this, and fixing it, I really appreciate it 😊
