### ISSUE TITLE
[BUG] ErrorProne compiler reports "MissingSummary" on @SuperBuilder

### ISSUE THREAD

**Issue by mmoayyed** [rzwitserloot/lombok#2730]
**Describe the bug**

ErrorProne compiler `2.5.1` complains about `MissingSummary` when `@SuperBuilder` is used in `1.18.18`.

**To Reproduce**

Stacktrace follows:

```
> Task :api:cas-server-core-api-authentication:compileJava
/Users/Misagh/Workspace/GitWorkspace/cas-server/api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/AuthenticationPolicyExecutionResult.java:18: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
@SuperBuilder
^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.5.1
     BugPattern: MissingSummary
     Stack Trace:
     java.lang.IllegalArgumentException: Start [-1] should not be less than zero
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:190)
        at com.google.errorprone.fixes.IndexedPosition.<init>(IndexedPosition.java:32)
        at com.google.errorprone.fixes.SuggestedFix$Builder.replace(SuggestedFix.java:213)
        at com.google.errorprone.bugpatterns.javadoc.MissingSummary.generateReturnFix(MissingSummary.java:139)
        at com.google.errorprone.bugpatterns.javadoc.MissingSummary.handle(MissingSummary.java:109)
        at com.google.errorprone.bugpatterns.javadoc.MissingSummary.matchMethod(MissingSummary.java:80)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:151)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:549)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
```

**Expected behavior**

Passing build.

**Version info (please complete the following information):**

- Lombok 1.18.18
- JDK 11.0.10
- Gradle 6.8.1
- ErrorProne 2.5.1

**Additional context**

- Disabling the `MissingSummary` with ErrorProne bypasses the issue.
- Works OK with Lombok 1.18.16

**Comment by Rawi01** [comment]
Can confirm that this does not work. 
This happens because lombok does not add start and end positons for generated Javadoc comments, most likely caused by the changes in #2684.

**Comment by rspilker** [comment]
@mmoayyed Can you please test the [edge release](https://projectlombok.org/download-edge) and report if that resolves the exception?

**Comment by mmoayyed** [comment]
Yes, the edge release certainly does remove the exception, but it does not fix the problem. After switching and instead of the stacktrace, I now see the following:

```
warning: [MissingSummary] A summary fragment is required; consider using the value of the @return block as a summary fragment instead.
@SuperBuilder
^
    (see https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
  Did you mean 'Returns {@code this}.'?
error: warnings found and -Werror specified
```

This is what the class structure looks like:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
@Getter
@SuperBuilder
@ToString
public class AuthenticationPolicyExecutionResult implements Serializable {
    private final boolean success;
}
```

I suspect the javadoc that is generated for the `success()` method is missing the appropriate summary. If I can help further, please let me know.

**Comment by sergeykad** [comment]
I started getting these errors for the regular `@Builder` after switching from Lombok 1.18.16 to 1.18.20


> Yes, the edge release certainly does remove the exception, but it does not fix the problem. After switching and instead of the stacktrace, I now see the following:
> 
> ```
> warning: [MissingSummary] A summary fragment is required; consider using the value of the @return block as a summary fragment instead.
> @SuperBuilder
> ^
>     (see https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
>   Did you mean 'Returns {@code this}.'?
> error: warnings found and -Werror specified

**Comment by rzwitserloot** [comment]
This sounds like a linting tool that requires javadoc on some node we generate. A few notes on this:

* It's a silly rule that you shouldn't be using. Forcing javadoc will result in folks writing pointless javadoc, which is a DRY violation. In a place that you can't unit test, even. I'm not in a position to tell you that this is the only resolution available, but it should perhaps indicate that we rate such issues as extremely low priority.
* We stick `@Generated` on lots of places, evidently the linter tool ignores those annotations. Unfortunately, linters don't make it easy for us. Are you aware of the various `lombok.config` options, and did you check your linter tool for any configuration in the vein of 'do not lint-check anything that is annotated with these annotations'? Is this a problem where these settings do not work, or is this a problem where it's not clear that they need to be set up?
* This doesn't sound related to the actual issue at all. A new issue should be filed with this 'MissingSummary' issue.
*

**Comment by hakanai** [comment]
Yes, ErrorProne is essentially a linting tool. It just plugs into the compiler so that it can run during the compilation process to save some build time.

And yes, it does ignore code with the `@Generated` annotation, if you configure it to do so, which we have.

But what's interesting with this one is that we only get the issue when we upgrade Lombok to the current version. The original reporter filed this against 1.18.18; we see it on 1.18.20. If we remain on 1.18.12, we don't get the issue. Actually, I was only upgrading to the newer version to see if it had fixed some _other_ issue with Lombok's generated code.

**Comment by hakanai** [comment]
Test repo: https://github.com/hakanai/errorprone-lombok-missingsummary

This build deliberately elevates MissingSummary to ERROR to make it easier to see when it fails.

If I edit Lombok version to 1.18.16 the build passes. Any later version fails.

If I comment out the elevation of MissingSummary to ERROR, the build passes (as it should) and yet when I inspect what IDEA sees when it decompiles the classfile, the code looks exactly the same as the earlier version, including all the annotations.

**Comment by rzwitserloot** [comment]
> So it apparently only occurs when the latest version of both are in use.

Thank you for figuring that one out. Sounds like that took some time!

And a test repo to boot. Much appreciated.

**Comment by rzwitserloot** [comment]
low-prio: While it's probably something we can fix (given the test repo), it remains catering to idiotic linting rules. If I could detect that rule was on I'd 'fix' this by emitting a warning that your linting tools are badly configured :)

**Comment by hakanai** [comment]
What MissingSummary usually flags is where you have put `@return` in the Javadoc, but then not put in any summary line.

In these cases, it's better to put that description as the summary, because that's what it shows in the summary list at the top of the Javadoc page.

https://github.com/google/error-prone/blob/master/docs/bugpattern/javadoc/MissingSummary.md

I kind of agree with this particular linter rule. If you're going to put in any description at all, it might as well be written in such a way that it appears in the summary.

**Comment by rzwitserloot** [comment]
> Also, all previous commentary about it being a DRY violation is a fallacy

No, unless you somehow turned that rule on to apply _only_ to generated code, which you obviously didn't.

**Comment by hakanai** [comment]
It's certainly a fallacy in this context, though, because we're talking about it being triggered from generated code.

**Comment by crutcher** [comment]
Ran into this again in 2023; so it's clearly not fixed at head.
The issue isn't which ones right; it's that they're both popular.
Lombok is upstream of Errorprone; and the fix could/should go here.

**Comment by Rawi01** [comment]
You can add `-XepDisableWarningsInGeneratedCode` to ignore the generated code.

**Comment by rspilker** [comment]
Unfortunately we've been pushing this forward for four or more years already. We  intended to fix this because we do find it important. On the other hand, both @rzwitserloot and I do not use ErrorProne.

@mmoayyed, I'm wondering if this issue is still present and relevant.

**Comment by mmoayyed** [comment]
@rspilker I don't think it's present anymore, or at least, I have not run into it in a long time. You're welcome to close the issue.
