### ISSUE TITLE
[BUG] Intellij IDEA 2020.3.2 AND 2020.2.4 + lombok 1.18.18 illegalArgumentException

### ISSUE THREAD

**Issue by JohannesBeranek** [rzwitserloot/lombok#2738]
**Describe the bug**
Play Framework 1 project works with Intellij IDEA 2020.2.4 + lombok 1.18.10. Upgrading to Intellij IDEA 2020.3.2 means we need to upgrade lombok. Neither 1.18.16 work (LOTS of errors during runtime), nor 1.18.18 (illegalArgumentException during runtime).
compiler is set to javac in IDEA, run options are
`-Dapplication.path="."  -javaagent:lib\lombok-1.18.10.jar -Xverify:none`

Also, quite important IMHO: We get the same issues with IDEA 2020.2.4 + lombok 1.18.18, so it's definitely an issue on lomboks end.

**To Reproduce**
Getting stack traces for several totally unrelated plugins, even cusom made ones, but they all look the same;

```
09:59:17,566 play.Logger ERROR ~ Error loading plugin LoadingPluginInfo{name='press.Plugin', index=100, url=file:/[redacted]/application/local-modules/press-1.0.36/app/play.plugins}
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:126)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:203)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:10525)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11706)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11930)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11887)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:10297)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:840)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:444)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:314)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:315)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:172)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:90)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at play.plugins.PluginCollection.loadPlugins(PluginCollection.java:173)
	at play.Play.init(Play.java:320)
	at play.server.Server.main(Server.java:162)

```

**Expected behavior**
Everything works

**Version info:**
 - 1.18.18
 - Intellij IDEA BOTH 2020.2.4 AND 2020.3.2, javac 11.0.9, Windows 10, AdoptOpenJDK 11 latest

**Comment by Rawi01** [comment]
Thanks for the bug report. Can you please double check that it really uses `javac`? The stacktrace contains `org.eclipse.jdt.internal.compiler` lines, it seems like you use `ecj` for some things which is obviously broken in the current version. I'm already working on a fix for that.

**Comment by JohannesBeranek** [comment]
@Rawi01 my fault, sorry. While compilation with javac in intellij works, this is actually being thrown from the play runtime compilation, which uses ecj, so I'm closing this issue, as it's the same as the ecj one.
