### ISSUE TITLE
Null Pointer Exception when lombok 1.18.18 is installed

### ISSUE THREAD

**Issue by dpolivaev** [rzwitserloot/lombok#2752]
eclipse.buildId=4.18.0.I20201202-1800
java.version=11.0.8
java.vendor=Azul Systems, Inc.

~~~~
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:148)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2624)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.nonStaticAccessToStaticMethod(ProblemReporter.java:7169)
	at lombok.eclipse.agent.PatchExtensionMethod$PostponedNonStaticAccessToStaticMethodError.fire(PatchExtensionMethod.java:154)
	at lombok.eclipse.agent.PatchExtensionMethod.resolveType(PatchExtensionMethod.java:371)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:126)
	at lombok.launch.PatchFixesHider$ExtensionMethod.resolveType(PatchFixesHider.java:308)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:1000)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:793)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1113)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolveUsing(Block.java:144)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.resolve(TryStatement.java:1209)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1493)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1618)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:662)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:902)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~~

**Comment by Rawi01** [comment]
Can you share a small code snippet that triggers this exception?

**Comment by dpolivaev** [comment]
I was able to extract it.
It does not contain any Lombok annotations, but it is sufficient to reproduce the crash.

~~~~java
package tests;


public class TestedClass  {
  public void method(){
      Derived derived = new Derived();

      derived.staticMethod();
  }
}

class Base {
    static String staticMethod() {
        return "";
    }
}

class Derived extends Base {
    
}
~~~~

**Comment by Rawi01** [comment]
Thanks, I will look into it

**Comment by dpolivaev** [comment]
Thanks. Let me know if you need any further information about the case.

**Comment by Rawi01** [comment]
I tried to reproduce the problem but it works as expected... I checked the lombok and eclipse code and might have figured out what is wrong here but I cannot test that. Does the snippet cause this exception in an otherwise emtpy workspace? Have you added any special plugins?

**Comment by dpolivaev** [comment]
I do not have the problem on a fresh workspace, but it comes when I import the attached  java compiler preferences from my main workspace. 
[jc.epf.zip](https://github.com/rzwitserloot/lombok/files/5987697/jc.epf.zip)

(I had to compress the file because of GitHub file type limitations)

**Comment by dpolivaev** [comment]
By the way, if you could create a patched lombok version I could check how it works in my environment.

**Comment by dpolivaev** [comment]
It looks like the exception comes if both of the following settings have values different from "ignore"

- Non-static access to static member
- Indirect access to static member

![Selection_021](https://user-images.githubusercontent.com/1558052/108054839-79048a00-704f-11eb-8ed3-0092c3a6517a.png)

Setting any of them to "ignore" works as a workaround

**Comment by Rawi01** [comment]
Thanks for the additional information, changing the severity level was the missing piece :smile: 
I have created a [patched lombok.jar](https://github.com/rzwitserloot/lombok/files/5994402/lombok.zip) if you want to test it.

**Comment by dpolivaev** [comment]
It looks good, the exception has gone with the patched version

**Comment by dpolivaev** [comment]
Thank you very much
