### ISSUE TITLE
jdk 9 NSFE

### ISSUE THREAD

**Issue by zhanhb** [rzwitserloot/lombok#931]
lombok version 1.16.6

```
java.lang.NoSuchFieldError: pid
    at lombok.javac.JavacAST.packageDeclaration(JavacAST.java:107)
    at lombok.javac.JavacAST.<init>(JavacAST.java:81)
    at lombok.javac.JavacTransformer.transform(JavacTransformer.java:67)
    at lombok.javac.apt.Processor.process(Processor.java:250)
    at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:115)
    at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:165)
    at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:58)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:827)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:739)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1047)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1154)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1150)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:838)
    at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
    at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
    at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
    ... 26 more
```

**Comment by askoning** [comment]
It seems like JDK9 has overhauled their tree structure quite a bit.

[The current JCCompilationUnit](http://hg.openjdk.java.net/jdk9/jdk9/langtools/file/3f3129007ded/src/jdk.compiler/share/classes/com/sun/tools/javac/tree/JCTree.java#l484) has no `pid` field anymore, but other means of retrieving the package declaration.

**Comment by rspilker** [comment]
I've just created issue #985 to handle all jdk9 related problems. Closing this issue.
