### ISSUE TITLE
creation of element failed

### ISSUE THREAD

**Issue by erikvaningen** [rzwitserloot/lombok#944]
Right mouse click in Eclipse on a class, New Junit test class. It will create an empty file with the error message creation of element failed. Index: 5, Size:5

**Comment by rzwitserloot** [comment]
Can not reproduce. Please give us some more detail; what version of lombok, what version of eclipse, paste the complete stack trace, etc. Will be marked as wontfix due to incomplete and not reproducible test case on December 20th.

**Comment by thorcode** [comment]
![image](https://cloud.githubusercontent.com/assets/4273886/11335603/95371a86-91ab-11e5-8e39-9f155f8578cf.png)

lombok-1.16.6
Eclipse Mars.1

The following data will be sent:

------
STATUS
------
pluginId            org.eclipse.jdt.junit
pluginVersion       3.8.0.v20150428-1340
code                4
severity            4
message             HIDDEN
fingerprint         614f7d8f

Exception:java.lang.reflect.InvocationTargetException: HIDDEN
	 at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:476)
	 at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
	 at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
	 at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1394)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	 at org.eclipse.ui.internal.progress.ProgressManager$5.run(ProgressManager.java:1228)
	 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	 at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
	 at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:1225)
	 at org.eclipse.jdt.internal.junit.wizards.JUnitWizard.finishPage(JUnitWizard.java:66)
	 at org.eclipse.jdt.internal.junit.wizards.NewTestCaseCreationWizard.performFinish(NewTestCaseCreationWizard.java:121)
	 at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
	 at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	 at org.eclipse.jface.window.Window.open(Window.java:803)
	 at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:136)
	 at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	 at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	 at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.IndexOutOfBoundsException: HIDDEN
	 at java.util.ArrayList.rangeCheck(null:-1)
	 at java.util.ArrayList.get(null:-1)
	 at org.eclipse.jdt.internal.formatter.TokenManager.get(TokenManager.java:68)
	 at org.eclipse.jdt.internal.formatter.TokenManager.findIndex(TokenManager.java:161)
	 at org.eclipse.jdt.internal.formatter.TokenManager.firstIndexIn(TokenManager.java:188)
	 at org.eclipse.jdt.internal.formatter.TokenManager.firstTokenIn(TokenManager.java:194)
	 at org.eclipse.jdt.internal.formatter.SpacePreparator.visit(SpacePreparator.java:201)
	 at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:611)
	 at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	 at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	 at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	 at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	 at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareSpaces(DefaultCodeFormatter.java:350)
	 at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:193)
	 at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:155)
	 at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:139)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatString(ASTRewriteFormatter.java:246)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.formatNode(ASTRewriteFormatter.java:376)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteFormatter.getFormattedResult(ASTRewriteFormatter.java:187)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.doTextInsert(ASTRewriteAnalyzer.java:1357)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:647)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer$ListRewriter.rewriteList(ASTRewriteAnalyzer.java:802)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.rewriteParagraphList(ASTRewriteAnalyzer.java:1175)
	 at org.eclipse.jdt.internal.core.dom.rewrite.ASTRewriteAnalyzer.visit(ASTRewriteAnalyzer.java:1811)
	 at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:453)
	 at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	 at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.internalRewriteAST(ASTRewrite.java:302)
	 at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:291)
	 at org.eclipse.jdt.internal.core.CreateElementInCUOperation.generateNewCompilationUnitAST(CreateElementInCUOperation.java:174)
	 at org.eclipse.jdt.internal.core.CreateElementInCUOperation.executeOperation(CreateElementInCUOperation.java:127)
	 at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:729)
	 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	 at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:794)
	 at org.eclipse.jdt.internal.core.SourceType.createMethod(SourceType.java:168)
	 at org.eclipse.jdt.junit.wizards.NewTestCaseWizardPageOne.createTestMethod(NewTestCaseWizardPageOne.java:976)
	 at org.eclipse.jdt.junit.wizards.NewTestCaseWizardPageOne.createTestMethodStubs(NewTestCaseWizardPageOne.java:897)
	 at org.eclipse.jdt.junit.wizards.NewTestCaseWizardPageOne.createTypeMembers(NewTestCaseWizardPageOne.java:753)
	 at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.createType(NewTypeWizardPage.java:2207)
	 at org.eclipse.jdt.ui.wizards.NewTypeWizardPage$7.run(NewTypeWizardPage.java:2699)
	 at org.eclipse.ui.actions.WorkspaceModifyDelegatingOperation.execute(WorkspaceModifyDelegatingOperation.java:70)
	 at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
	 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	 at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
	 at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
	 at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
	 at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
	 at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1394)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	 at org.eclipse.ui.internal.progress.ProgressManager$5.run(ProgressManager.java:1228)
	 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	 at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
	 at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:1225)
	 at org.eclipse.jdt.internal.junit.wizards.JUnitWizard.finishPage(JUnitWizard.java:66)
	 at org.eclipse.jdt.internal.junit.wizards.NewTestCaseCreationWizard.performFinish(NewTestCaseCreationWizard.java:121)
	 at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
	 at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	 at org.eclipse.jface.window.Window.open(Window.java:803)
	 at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:136)
	 at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	 at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	 at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

------
REPORT
------
anonymousId         3cbe48d6-e48d-42f4-92d6-36376a8433fb
comment             
eclipseBuildId      4.5.1.M20150904-0015
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0_25-b18
osgiWs              win32
osgiOs              Windows8
osgiOsVersion       6.2.0
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.resources
version             3.10.1.v20150725-1910

name                org.eclipse.core.runtime
version             3.11.1.v20150903-1804

name                org.eclipse.e4.ui.workbench
version             1.3.0.v20150531-1948

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150504-0621

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150511-1540

name                org.eclipse.jdt.core
version             3.11.1.v20150902-1521

name                org.eclipse.jdt
version             3.11.1.v20150904-0015

name                org.eclipse.jdt.junit
version             3.8.0.v20150428-1340

name                org.eclipse.jdt.ui
version             3.11.1.v20150827-1306

name                org.eclipse.jface
version             3.11.0.v20150602-1400

name                org.eclipse.swt
version             3.104.1.v20150825-0743

name                org.eclipse.ui
version             3.107.0.v20150507-1945

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150825-2158

**Comment by erikvaningen** [comment]
I am on Eclipse Java EE IDE for Web Developers. Version: Mars.1 Release (4.5.1) Build id: 20150924-1200. 

Problem was solved by migrating from Lombok 1.16.2 to 1.16.6, replacing also the lombok.jar in the eclipse directory.

**Comment by rspilker** [comment]
Thanks for the feedback

**Comment by thorcode** [comment]
Thanks.  My gradle script didn't move the lastest lombok.jar into the
eclipse folder once it was updated it started to work.

Regards,
John
